# This file is dot-sourced by Invoke-AutomatedChecks.ps1 for Pomodoro runtime tick boundary assertions.

function Invoke-PomodoroRuntimeBoundaryCheck([string]$ModulesDir) {
    $runtime = Join-Path $ModulesDir "PomodoroRuntime.ps1"
    $runtimeQueries = Join-Path $ModulesDir "PomodoroRuntime.Queries.ps1"
    $runtimeState = Join-Path $ModulesDir "PomodoroRuntimeState.ps1"
    $format = Join-Path $ModulesDir "PomodoroFormat.ps1"
    $session = Join-Path $ModulesDir "PomodoroSession.ps1"
    $planning = Join-Path $ModulesDir "PomodoroPlanning.ps1"
    $engine = Join-Path $ModulesDir "PomodoroEngine.ps1"
    $timerSettings = Join-Path $ModulesDir "Views.Timer.SettingsDialog.ps1"
    $selfTestPomodoro = Join-Path $ModulesDir "SelfTest.Pomodoro.ps1"
    $settingsView = Join-Path $ModulesDir "Views.Settings.ps1"
    $settingsApply = Join-Path $ModulesDir "Views.Settings.Apply.ps1"
    $starterSettings = Join-Path $ModulesDir "Views.Settings.Starter.ps1"
    $inlineCountdown = Join-Path $ModulesDir "PomodoroInlineCountdown.ps1"
    $audio = Join-Path $ModulesDir "PomodoroAudio.ps1"
    $uiTimer = Join-Path $ModulesDir "UiTimer.ps1"
    $timerActions = Join-Path $ModulesDir "Views.Timer.Actions.ps1"
    foreach ($requiredFile in @($runtime, $runtimeQueries, $runtimeState, $format, $session, $planning, $engine, $timerSettings, $selfTestPomodoro, $settingsView, $settingsApply, $starterSettings, $inlineCountdown, $audio, $uiTimer, $timerActions)) { Test-RequiredFile $requiredFile }
    . (Join-Path $ModulesDir "ModuleLoadOrder.ps1"); $loadOrder = Get-TaskPomodoroModuleLoadOrder
    foreach ($moduleName in @("PomodoroSession.ps1", "PomodoroPlanning.ps1", "PomodoroEvents.ps1", "PomodoroFormat.ps1", "PomodoroEngine.ps1", "PomodoroStarter.ps1", "PomodoroWorkflow.ps1", "PomodoroAudio.ps1", "PomodoroRuntime.ps1", "PomodoroRuntime.Queries.ps1", "PomodoroRuntimeState.ps1", "PomodoroInlineCountdown.ps1", "Views.Timer.Actions.ps1", "Views.Timer.ps1", "Views.Settings.Starter.ps1", "Views.Settings.Apply.ps1", "Views.Settings.ps1", "UiTimer.ps1")) { if ([Array]::IndexOf($loadOrder, $moduleName) -lt 0) { throw "ModuleLoadOrder.ps1 missing $moduleName" } }
    foreach ($formatConsumer in @("PomodoroInlineCountdown.ps1", "PomodoroStarter.ps1", "Views.Task.Menu.ps1", "Views.Timer.ps1", "Views.Timer.Starter.ps1", "SelfTest.Configuration.ps1")) { if ([Array]::IndexOf($loadOrder, "PomodoroFormat.ps1") -gt [Array]::IndexOf($loadOrder, $formatConsumer)) { throw "PomodoroFormat.ps1 must load before $formatConsumer" } }
    foreach ($sessionConsumer in @("PomodoroFormat.ps1", "PomodoroStarter.ps1", "Views.Settings.Starter.ps1")) { if ([Array]::IndexOf($loadOrder, "PomodoroSession.ps1") -gt [Array]::IndexOf($loadOrder, $sessionConsumer)) { throw "PomodoroSession.ps1 must load before $sessionConsumer" } }
    foreach ($sourceModule in @("PomodoroEngine.ps1", "PomodoroStarter.ps1", "PomodoroWorkflow.ps1")) { if ([Array]::IndexOf($loadOrder, $sourceModule) -gt [Array]::IndexOf($loadOrder, "PomodoroRuntime.ps1")) { throw "PomodoroRuntime.ps1 must load after $sourceModule" } }
    if ([Array]::IndexOf($loadOrder, "PomodoroAudio.ps1") -gt [Array]::IndexOf($loadOrder, "PomodoroRuntime.ps1")) { throw "PomodoroRuntime.ps1 must load after PomodoroAudio.ps1" }
    if ([Array]::IndexOf($loadOrder, "PomodoroRuntime.Queries.ps1") -gt [Array]::IndexOf($loadOrder, "PomodoroRuntimeState.ps1")) { throw "PomodoroRuntimeState.ps1 must load after PomodoroRuntime.Queries.ps1" }
    if ([Array]::IndexOf($loadOrder, "PomodoroRuntime.ps1") -gt [Array]::IndexOf($loadOrder, "UiTimer.ps1")) { throw "PomodoroRuntime.ps1 must load before UiTimer.ps1" }
    if ([Array]::IndexOf($loadOrder, "Views.Timer.Actions.ps1") -gt [Array]::IndexOf($loadOrder, "UiTimer.ps1")) { throw "Views.Timer.Actions.ps1 must load before UiTimer.ps1" }

    $formatRaw = Get-Content -LiteralPath $format -Encoding UTF8 -Raw
    foreach ($required in @("function Format-Time", "function Get-TaskStarterLabel", "function Get-TaskStarterAgainText", "{0:00}:{1:00}", "TaskStarterMenu")) { if ($formatRaw -notlike "*$required*") { throw "PomodoroFormat.ps1 missing text formatting marker: $required" } }
    Test-FileDoesNotContain $engine @("function Format-Time") "PomodoroEngine.ps1 must not own Pomodoro time display formatting."
    $runtimeRaw = Get-Content -LiteralPath $runtime -Encoding UTF8 -Raw
    foreach ($required in @("function Clear-PomodoroRuntimeCurrentTask", "function Set-PomodoroRuntimeCurrentTask", "function Clear-PomodoroRuntimePlannedDuration", "function Set-PomodoroRuntimeIdleDuration", "function Update-PomodoroRuntimeDuration", "function Update-PomodoroRuntimeAudioAfterSettingsChange", "function Update-PomodoroRuntimeAfterGeneralSettingsChange", "function Start-PomodoroRuntimePhase", "function Pause-PomodoroRuntimePhase", "function Resume-PomodoroRuntimePhase", "function Set-PomodoroRuntimeIdleWorkState", "function Update-PomodoroRuntimeTick", "function Start-PomodoroRuntimeCompletion", "function Complete-PomodoroRuntimeCompletion", "function Test-PomodoroRuntimeTaskInvalidationNeeded", "Update-BackgroundAudioFade", "TimerCompletionInProgress")) { if ($runtimeRaw -notlike "*$required*") { throw "PomodoroRuntime.ps1 missing required marker: $required" } }
    Test-FileDoesNotContain $runtime @("System.Windows.Forms", "MessageBox", "InputBox", "Invoke-AppActionResult", "Complete-PomodoroFromUi", "Update-TimerLabels", "TaskListBox", "Render-CurrentView", "Set-Status") "PomodoroRuntime.ps1 must not render UI or invoke UI action wrappers."
    Test-FileDoesNotContain $runtime @("function Test-PomodoroRuntimeIdle", "function Test-PomodoroRuntimeStarterPhase", "function Test-PomodoroRuntimeStarterForTask", "function Test-PomodoroRuntimePaused", "function Test-PomodoroRuntimeRunning", "function Get-PomodoroRuntimeCurrentTaskId", "function Get-PomodoroRuntimeEngineSnapshot", "function Get-PomodoroRuntimeTimerViewSnapshot", "function Get-PomodoroRuntimeCompletionNotificationSnapshot", "function Test-PomodoroRuntimeBreakPhase", "function Get-PomodoroRuntimeInlineCountdownSnapshot") "PomodoroRuntime.ps1 must keep read-only query facades in PomodoroRuntime.Queries.ps1."
    $runtimeQueriesRaw = Get-Content -LiteralPath $runtimeQueries -Encoding UTF8 -Raw
    foreach ($required in @("function Test-PomodoroRuntimeIdle", "function Test-PomodoroRuntimeStarterPhase", "function Test-PomodoroRuntimeStarterForTask", "function Test-PomodoroRuntimePaused", "function Test-PomodoroRuntimeRunning", "function Get-PomodoroRuntimeCurrentTaskId", "function Get-PomodoroRuntimeEngineSnapshot", "function Get-PomodoroRuntimeTimerViewSnapshot", "function Get-PomodoroRuntimeCompletionNotificationSnapshot", "function Test-PomodoroRuntimeBreakPhase", "function Get-PomodoroRuntimeInlineCountdownSnapshot")) { if ($runtimeQueriesRaw -notlike "*$required*") { throw "PomodoroRuntime.Queries.ps1 missing required marker: $required" } }
    Test-FileDoesNotContain $runtimeQueries @('$script:TimerState =', '$script:TimerPhase =', '$script:SecondsRemaining =', '$script:PomodoroEndAt =', '$script:PomodoroStartedAt =', '$script:PomodoroStartedAtDate =', '$script:CurrentPhasePlannedMinutes =', '$script:CurrentPomodoroTaskId =', '$script:CurrentPomodoroTaskTitle =', "System.Windows.Forms", "MessageBox", "InputBox", "Start-BackgroundAudio", "Stop-BackgroundAudio", "Save-Settings", "Save-GeneralSettings", "Update-TimerLabels", "Render-CurrentView", "Set-Status") "PomodoroRuntime.Queries.ps1 must stay read-only and side-effect free."
    $runtimeStateRaw = Get-Content -LiteralPath $runtimeState -Encoding UTF8 -Raw
    foreach ($required in @("function Get-PomodoroRuntimeStateFile", "function Get-PomodoroRuntimeStateSnapshot", "function Save-PomodoroRuntimeState", "function Clear-PomodoroRuntimeStateFile", "function Restore-PomodoroRuntimeState", "Get-PomodoroRuntimeTimerViewSnapshot", "Write-JsonAtomic", "Backup-DataFile", "PauseThresholdsTriggered", "SavedAt", "PausedAt")) { if ($runtimeStateRaw -notlike "*$required*") { throw "PomodoroRuntimeState.ps1 missing restart recovery marker: $required" } }
    Test-FileDoesNotContain $runtimeState @("System.Windows.Forms", "MessageBox", "InputBox", "Invoke-AppActionResult", "Complete-PomodoroFromUi", "Update-TimerLabels", "TaskListBox", "Render-CurrentView", "Set-Status", "Start-BackgroundAudio", "Stop-BackgroundAudio") "PomodoroRuntimeState.ps1 must persist runtime state without UI or audio side effects."
    if (-not $runtimeRaw.Contains('Update-BackgroundAudioFade $remaining ([string]$script:TimerPhase)')) { throw "PomodoroRuntime.ps1 must pass the current phase into Update-BackgroundAudioFade." }
    Test-FileDoesNotContain $audio @('$script:TimerPhase') "PomodoroAudio.ps1 must receive phase from PomodoroRuntime.ps1 instead of reading runtime private fields."
    $audioRaw = Get-Content -LiteralPath $audio -Encoding UTF8 -Raw
    if (-not $audioRaw.Contains('function Update-BackgroundAudioFade([int]$SecondsRemaining, [string]$Phase)')) { throw "PomodoroAudio.ps1 must keep Update-BackgroundAudioFade phase parameter." }
    foreach ($stateMachineFile in @("PomodoroEngine.ps1", "PomodoroStarter.ps1")) { Test-FileDoesNotContain (Join-Path $ModulesDir $stateMachineFile) @('$script:TimerState =', '$script:TimerPhase =', '$script:SecondsRemaining =', '$script:PomodoroEndAt =', '$script:PomodoroStartedAt =', '$script:PomodoroStartedAtDate =', '$script:CurrentPhasePlannedMinutes =', '$script:CurrentPomodoroTaskId =', '$script:CurrentPomodoroTaskTitle =') "$stateMachineFile must write Pomodoro runtime fields through PomodoroRuntime.ps1 facade." }
    Test-FileDoesNotContain (Join-Path $ModulesDir "PomodoroEngine.ps1") @('$script:TimerState', '$script:TimerPhase', '$script:CurrentPomodoroTaskId', '$script:PomodoroStartedAt', '$script:PomodoroStartedAtDate') "PomodoroEngine.ps1 must read runtime state through PomodoroRuntime.Queries.ps1 facade."
    $engineRaw = Get-Content -LiteralPath $engine -Encoding UTF8 -Raw
    foreach ($required in @("Get-PomodoroRuntimeEngineSnapshot", "Test-PomodoroRuntimeRunning", "Get-PomodoroStartTaskBinding", "Get-PomodoroNextRoundDecision")) { if ($engineRaw -notlike "*$required*") { throw "PomodoroEngine.ps1 must keep runtime/planning facade marker: $required" } }
    Test-FileDoesNotContain $engine @("Get-TaskById", "Get-TaskRemainingPomodoros", "Test-PomodoroSessionHasNextRound") "PomodoroEngine.ps1 must use PomodoroPlanning.ps1 for task binding and next-round planning decisions."
    $planningRaw = Get-Content -LiteralPath $planning -Encoding UTF8 -Raw
    foreach ($required in @("function Test-PomodoroStartNeedsPlan", "function Apply-PomodoroStartPlanIfNeeded", "function Test-PomodoroTaskNeedsAdditionalPlan", "function Add-PomodoroEstimateForTask", "function Get-PomodoroTaskBinding", "function Get-PomodoroStartTaskBinding", "function Get-PomodoroStarterTaskBinding", "function Get-PomodoroNextRoundDecision", "Test-PomodoroSessionHasNextRound", "Get-TaskRemainingPomodoros", "Get-TaskById", "estimatedPomodoroCount", "Add-TaskEstimatedPomodoros", "Test-TaskIsCompleted", "HasTask", "HasNext", "TaskId", "TaskTitle")) { if ($planningRaw -notlike "*$required*") { throw "PomodoroPlanning.ps1 missing task-binding/next-round planning marker: $required" } }
    Test-FileDoesNotContain (Join-Path $ModulesDir "PomodoroStarter.ps1") @('$script:TimerState', '$script:TimerPhase', '$script:CurrentPomodoroTaskId', "Get-TaskById", "function Get-TaskStarterText", "function Get-TaskStarterLabel", "function Get-TaskStarterAgainText", "function Get-TaskStarterMinutes", "function Get-TaskStarterSeconds", "function Get-TaskStarterDefaultAction", "TaskStarterMenu", '$script:Settings.StarterMinutes', "StarterDefaultAction", "Another ", "5YaN5YGa", "5YiG6ZKf") "PomodoroStarter.ps1 must read runtime state through PomodoroRuntime.Queries.ps1, task bindings through PomodoroPlanning.ps1, starter labels through PomodoroFormat.ps1, and completion defaults through PomodoroWorkflow.ps1."
    $starterRaw = Get-Content -LiteralPath (Join-Path $ModulesDir "PomodoroStarter.ps1") -Encoding UTF8 -Raw
    foreach ($required in @("Test-PomodoroRuntimeIdle", "Test-PomodoroRuntimeStarterPhase", "Test-PomodoroRuntimeStarterForTask", "Get-PomodoroRuntimeCurrentTaskId", "Get-PomodoroStarterTaskBinding")) { if ($starterRaw -notlike "*$required*") { throw "PomodoroStarter.ps1 must keep runtime/planning facade marker: $required" } }
    Test-FileDoesNotContain $session @('$script:TimerPhase', '$script:SecondsRemaining =', '$script:CurrentPhasePlannedMinutes =', '$script:PomodoroEndAt =') "PomodoroSession.ps1 must delegate phase queries and duration field writes through PomodoroRuntime.ps1 facade."
    foreach ($settingsFile in @($settingsView, $settingsApply, $starterSettings)) { Test-FileDoesNotContain $settingsFile @('$script:TimerState', '$script:TimerPhase', '$script:SecondsRemaining =', '$script:CurrentPhasePlannedMinutes =', '$script:PomodoroEndAt =') "$([System.IO.Path]::GetFileName($settingsFile)) must not read or own Pomodoro runtime fields." }
    $sessionRaw = Get-Content -LiteralPath $session -Encoding UTF8 -Raw
    foreach ($required in @("Clear-PomodoroRuntimePlannedDuration", "Test-PomodoroRuntimeBreakPhase", "Update-PomodoroRuntimeDuration", "function Get-TaskStarterMinutes", "StarterMinutes")) { if ($sessionRaw -notlike "*$required*") { throw "PomodoroSession.ps1 must delegate duration changes and own timer duration reads: $required" } }
    foreach ($required in @("Get-PomodoroSessionStartedCount", "Get-PomodoroSessionMaxRounds", "Test-PomodoroSessionStartedForDifferentTask", "Add-PomodoroSessionStartedCount", "Test-PomodoroSessionHasNextRound")) { if ($sessionRaw -notlike "*$required*") { throw "PomodoroSession.ps1 must keep session round facade marker: $required" } }
    foreach ($sessionConsumer in @($engine, $timerSettings, $selfTestPomodoro)) { Test-FileDoesNotContain $sessionConsumer @('$script:PomodoroSessionStartedCount', '$script:PomodoroSessionMaxRounds') "$([System.IO.Path]::GetFileName($sessionConsumer)) must read/update Pomodoro session rounds through PomodoroSession.ps1 facade." }
    foreach ($required in @("Test-PomodoroSessionStartedForDifferentTask", "Add-PomodoroSessionStartedCount")) { if ($engineRaw -notlike "*$required*") { throw "PomodoroEngine.ps1 must keep session round facade marker: $required" } }
    $timerSettingsRaw = Get-Content -LiteralPath $timerSettings -Encoding UTF8 -Raw
    if ($timerSettingsRaw -notlike "*Get-PomodoroSessionMaxRounds*") { throw "Views.Timer.SettingsDialog.ps1 must read max rounds through PomodoroSession.ps1 facade." }
    $selfTestPomodoroRaw = Get-Content -LiteralPath $selfTestPomodoro -Encoding UTF8 -Raw
    if ($selfTestPomodoroRaw -notlike "*Get-PomodoroSessionStartedCount*") { throw "SelfTest.Pomodoro.ps1 must read started rounds through PomodoroSession.ps1 facade." }
    foreach ($settingsFile in @($settingsView, $settingsApply)) { $settingsRaw = Get-Content -LiteralPath $settingsFile -Encoding UTF8 -Raw; if ($settingsRaw -notlike "*Update-PomodoroRuntimeAfterGeneralSettingsChange*") { throw "$([System.IO.Path]::GetFileName($settingsFile)) must delegate post-save runtime refresh through PomodoroRuntime.ps1." } }
    $starterSettingsRaw = Get-Content -LiteralPath $starterSettings -Encoding UTF8 -Raw
    if ($starterSettingsRaw -notlike "*Update-PomodoroRuntimeAudioAfterSettingsChange*") { throw "Views.Settings.Starter.ps1 must delegate audio refresh through PomodoroRuntime.ps1." }
    Test-FileDoesNotContain $inlineCountdown @('$script:TimerState', '$script:TimerPhase', '$script:CurrentPomodoroTaskId', '$script:SecondsRemaining') "PomodoroInlineCountdown.ps1 must query PomodoroRuntime.ps1 instead of reading runtime private fields."
    $inlineRaw = Get-Content -LiteralPath $inlineCountdown -Encoding UTF8 -Raw
    foreach ($required in @("Get-PomodoroRuntimeInlineCountdownSnapshot", "Format-Time")) { if ($inlineRaw -notlike "*$required*") { throw "PomodoroInlineCountdown.ps1 must keep runtime query and text formatting marker: $required" } }

    $uiTimerRaw = Get-Content -LiteralPath $uiTimer -Encoding UTF8 -Raw
    foreach ($required in @("Update-PomodoroRuntimeTick", "Complete-PomodoroTickFromUi", "Update-TimerLabels")) { if ($uiTimerRaw -notlike "*$required*") { throw "UiTimer.ps1 must delegate Pomodoro tick through runtime/action facade: $required" } }
    Test-FileDoesNotContain $uiTimer @("PomodoroEndAt", "TimerCompletionInProgress", "Update-BackgroundAudioFade", "Complete-PomodoroRuntimeCompletion", "Complete-PomodoroFromUi", '$script:SecondsRemaining =') "UiTimer.ps1 must not own Pomodoro remaining-time calculation or completion guard."
    $timerActionsRaw = Get-Content -LiteralPath $timerActions -Encoding UTF8 -Raw
    foreach ($required in @("function Complete-PomodoroTickFromUi", "Complete-PomodoroRuntimeCompletion", "Complete-PomodoroFromUi")) { if ($timerActionsRaw -notlike "*$required*") { throw "Views.Timer.Actions.ps1 must own Pomodoro tick completion UI action marker: $required" } }
    "Pomodoro runtime tick is separated from global UI timer"
}
