# This file is dot-sourced by Invoke-AutomatedChecks.ps1 for translation module boundary assertions.

function Invoke-WatermarkTranslationBoundaryCheck([string]$ModulesDir) {
    $translationPlatform = Join-Path $ModulesDir "TranslationPlatform.ps1"
    $legacyTranslationPlatform = Join-Path $ModulesDir "WatermarkTranslation.Platform.ps1"
    $translationCore = Join-Path $ModulesDir "WatermarkTranslation.ps1"
    $translationRuntime = Join-Path $ModulesDir "TranslationRuntime.ps1"
    $translationBridge = Join-Path $ModulesDir "TranslationBridge.ps1"
    $translationDictionaryIndex = Join-Path $ModulesDir "TranslationDictionaryIndex.ps1"
    $translationDictionary = Join-Path $ModulesDir "TranslationDictionary.ps1"
    $legacyTranslationDictionary = Join-Path $ModulesDir "WatermarkTranslation.Dictionary.ps1"
    $translationSurface = Join-Path $ModulesDir "WatermarkTranslation.Surface.ps1"
    $translationSurfaceFacade = Join-Path $ModulesDir "TranslationSurface.ps1"
    $translationSelection = Join-Path $ModulesDir "TranslationSelection.ps1"
    $watermarkMenu = Join-Path $ModulesDir "WatermarkMode.Menu.ps1"
    $watermarkMode = Join-Path $ModulesDir "WatermarkMode.ps1"
    $selfTestUi = Join-Path $ModulesDir "SelfTest.Ui.ps1"
    foreach ($requiredFile in @($translationPlatform, $legacyTranslationPlatform, $translationCore, $translationRuntime, $translationBridge, $translationDictionaryIndex, $translationDictionary, $legacyTranslationDictionary, $translationSurface, $translationSurfaceFacade, $translationSelection, $watermarkMenu, $watermarkMode, $selfTestUi)) { Test-RequiredFile $requiredFile }
    . (Join-Path $ModulesDir "ModuleLoadOrder.ps1")
    $loadOrder = Get-TaskPomodoroModuleLoadOrder
    foreach ($moduleName in @("TranslationPlatform.ps1", "WatermarkTranslation.Platform.ps1", "TranslationDictionaryIndex.ps1", "TranslationDictionary.ps1", "TranslationDictionaryInstall.ps1", "WatermarkTranslation.Dictionary.ps1", "WatermarkTranslation.Surface.ps1", "TranslationSurface.ps1", "TranslationSelection.ps1", "TranslationBridge.ps1", "WatermarkTranslation.ps1", "TranslationRuntime.ps1", "WatermarkMode.ps1", "WatermarkRuntime.ps1", "WatermarkMode.Menu.ps1")) { if ([Array]::IndexOf($loadOrder, $moduleName) -lt 0) { throw "ModuleLoadOrder.ps1 missing $moduleName" } }
    if ([Array]::IndexOf($loadOrder, "TranslationDictionaryIndex.ps1") -gt [Array]::IndexOf($loadOrder, "TranslationDictionary.ps1")) { throw "TranslationDictionaryIndex.ps1 must load before TranslationDictionary.ps1" }
    if ([Array]::IndexOf($loadOrder, "TranslationPlatform.ps1") -gt [Array]::IndexOf($loadOrder, "WatermarkTranslation.Platform.ps1")) { throw "TranslationPlatform.ps1 must load before WatermarkTranslation.Platform.ps1" }
    foreach ($platformDependent in @("TranslationProviders.ps1", "TranslationSurface.ps1", "TranslationSelection.ps1", "TranslationRuntime.ps1", "TranslationSettings.ps1", "WatermarkTranslation.ps1")) { if ([Array]::IndexOf($loadOrder, "TranslationPlatform.ps1") -gt [Array]::IndexOf($loadOrder, $platformDependent)) { throw "TranslationPlatform.ps1 must load before $platformDependent" } }
    if ([Array]::IndexOf($loadOrder, "TranslationDictionary.ps1") -gt [Array]::IndexOf($loadOrder, "WatermarkTranslation.Dictionary.ps1")) { throw "TranslationDictionary.ps1 must load before WatermarkTranslation.Dictionary.ps1" }
    if ([Array]::IndexOf($loadOrder, "WatermarkTranslation.Dictionary.ps1") -gt [Array]::IndexOf($loadOrder, "WatermarkTranslation.ps1")) { throw "WatermarkTranslation.Dictionary.ps1 must load before WatermarkTranslation.ps1" }
    if ([Array]::IndexOf($loadOrder, "TranslationSurface.ps1") -gt [Array]::IndexOf($loadOrder, "WatermarkTranslation.Surface.ps1")) { throw "TranslationSurface.ps1 must load before WatermarkTranslation.Surface.ps1" }
    if ([Array]::IndexOf($loadOrder, "TranslationSurface.ps1") -gt [Array]::IndexOf($loadOrder, "TranslationBridge.ps1")) { throw "TranslationSurface.ps1 must load before TranslationBridge.ps1" }
    if ([Array]::IndexOf($loadOrder, "TranslationBridge.ps1") -gt [Array]::IndexOf($loadOrder, "WatermarkTranslation.ps1")) { throw "TranslationBridge.ps1 must load before WatermarkTranslation.ps1" }
    if ([Array]::IndexOf($loadOrder, "TranslationPlatform.ps1") -gt [Array]::IndexOf($loadOrder, "TranslationSelection.ps1") -or [Array]::IndexOf($loadOrder, "TranslationSelection.ps1") -gt [Array]::IndexOf($loadOrder, "TranslationBridge.ps1")) { throw "TranslationSelection.ps1 must load after platform and before TranslationBridge.ps1" }
    if ([Array]::IndexOf($loadOrder, "TranslationBridge.ps1") -gt [Array]::IndexOf($loadOrder, "TranslationRuntime.ps1")) { throw "TranslationBridge.ps1 must load before TranslationRuntime.ps1" }
    if ([Array]::IndexOf($loadOrder, "WatermarkMode.ps1") -gt [Array]::IndexOf($loadOrder, "WatermarkRuntime.ps1")) { throw "WatermarkMode.ps1 must load before WatermarkRuntime.ps1" }
    if ([Array]::IndexOf($loadOrder, "TranslationRuntime.ps1") -gt [Array]::IndexOf($loadOrder, "WatermarkMode.Menu.ps1")) { throw "TranslationRuntime.ps1 must load before WatermarkMode.Menu.ps1" }
    if ([Array]::IndexOf($loadOrder, "WatermarkRuntime.ps1") -gt [Array]::IndexOf($loadOrder, "WatermarkMode.Menu.ps1")) { throw "WatermarkRuntime.ps1 must load before WatermarkMode.Menu.ps1" }

    Test-FileDoesNotContain $translationCore @("function Set-TranslationComboSelection", "function New-TranslationProviderCombo", "function Add-TranslationSettingsRows", "function New-TranslationSettingsPanel", "function Show-TranslationSettingsDialog", "function Apply-TranslationSettingsControls", "function Test-TranslationConnection", "function Show-TranslationDictionaryImportDialog") "WatermarkTranslation.ps1 must keep runtime translation logic separate from settings UI."
    Test-FileDoesNotContain $translationCore @("function Get-WatermarkTranslationBuiltinDictionaryPath", "function Get-WatermarkTranslationUserDictionaryPath", "function Convert-TranslationDefinitionToShortText", "function Add-WatermarkTranslationDictionaryFile", "function Load-WatermarkTranslationDictionary", "function Get-WatermarkTranslationLookupCandidates", "function Get-WatermarkTranslationLocalResult") "WatermarkTranslation.ps1 must keep dictionary lookup separate from runtime translation orchestration."
    Test-FileDoesNotContain $translationCore @("function Ensure-WatermarkTranslationTypes", "function Protect-TranslationSecret", "function Unprotect-TranslationSecret", "function Get-ScreenSafePoint", "function Set-WatermarkTranslationDetailLocation", "function Get-WatermarkTranslationFontSize", "function Ensure-WatermarkTranslationForms", "function Format-WatermarkTranslationDetail", "function Show-WatermarkTranslationResult", "Show-WatermarkTranslationResult", "function Hide-WatermarkTranslationResultFromTimer", "function Hide-WatermarkTranslationSurfaces", "Hide-WatermarkTranslationSurfaces", "function Dispose-WatermarkTranslationSurfaces", "Dispose-WatermarkTranslationSurfaces", "function Add-WatermarkMenuAction", "function Show-WatermarkMenu", "TaskPomodoroNoActivateForm", "TaskPomodoroTranslationDetailForm", "FormBorderStyle", "System.Windows.Automation", "Clipboard]", "GetClipboardSequenceNumber", "Get-WatermarkTranslationSelectionFromElement", "function Get-WatermarkTranslationSelection ", "Start-WatermarkTranslationClipboardListener", "Stop-WatermarkTranslationClipboardListener", "Update-WatermarkTranslationClipboard", "Register-AppNotificationHandler", "Clear-AppNotificationHandlers", "Show-TranslationSurfaceResult", "Get-TranslationSelection", "Invoke-TranslationWorkflowRequest") "WatermarkTranslation.ps1 must keep platform, overlay rendering, selection adapters, bridge work, and menu helpers in dedicated modules."
    foreach ($translationSaveModule in @($translationCore)) { Test-FileDoesNotContain $translationSaveModule @("Save-Settings", "-PreserveWindow") "Watermark translation modules must use SettingsWorkflow translation save functions instead of Save-Settings directly." }
    $runtimeRaw = Get-Content -LiteralPath $translationRuntime -Encoding UTF8 -Raw
    foreach ($required in @("function Get-TranslationRuntimeTimer", "function Test-TranslationRuntimeActive", "function Test-TranslationRuntimeTimerCreated", "function Test-TranslationRuntimeTimerEnabled", "function Ensure-TranslationRuntimeTimer", "function Start-TranslationRuntime", "Register-TranslationNotificationHandlers", "Show-TranslationText", "function Stop-TranslationRuntime", "Clear-TranslationNotificationHandlers", "function Suspend-TranslationRuntimeForSettings", "function Resume-TranslationRuntimeAfterSettings", "function Update-TranslationRuntimeAfterSettingsChanged")) { if ($runtimeRaw -notlike "*$required*") { throw "TranslationRuntime.ps1 missing required marker: $required" } }
    Test-FileDoesNotContain $translationCore @("function Ensure-WatermarkTranslationTimer", "WatermarkTranslationTimer", '$script:WatermarkTranslationMode', "Ensure-TranslationRuntimeTimer", "Start-TranslationClipboardListener", "Stop-TranslationClipboardListener", "Clear-TranslationLookupCache") "WatermarkTranslation.ps1 must leave lifecycle resources to TranslationRuntime.ps1."
    Test-FileDoesNotContain $translationRuntime @('$script:WatermarkTranslationMode', '$script:WatermarkTranslationTimer', '$script:WatermarkTranslationSettingsDialog', '$script:TranslationSettingsDialog') "TranslationRuntime.ps1 must use neutral runtime state fields and not own translation settings dialog state."
    $bridgeRaw = Get-Content -LiteralPath $translationBridge -Encoding UTF8 -Raw; foreach ($required in @("function Register-TranslationNotificationHandlers", "function Clear-TranslationNotificationHandlers", "function Show-TranslationText", "function Update-TranslationSelectionBridge", "Register-AppNotificationHandler", "Show-TranslationSurfaceResult", "Invoke-TranslationWorkflowRequest", "Get-TranslationSelection")) { if ($bridgeRaw -notlike "*$required*") { throw "TranslationBridge.ps1 missing bridge marker: $required" } }
    Test-FileDoesNotContain $translationBridge @("Invoke-RestMethod", "Save-Settings", "Save-GeneralSettings", "TaskFontSize", "WatermarkPrevious", "New-Object System.Windows.Forms.Timer", "Start-TranslationRuntime", "Stop-TranslationRuntime") "TranslationBridge.ps1 must not own provider calls, host state, or runtime resources."
    Test-FileDoesNotContain $selfTestUi @('$script:WatermarkTranslationMode', '$script:WatermarkTranslationTimer', '$script:WatermarkTranslationSettingsDialog') "SelfTest.Ui.ps1 must verify translation runtime state through TranslationRuntime facade functions."
    $translationHostLayoutTokens = @("Enter-WatermarkMode", "Exit-WatermarkMode", "Toggle-WatermarkMode", "Start-WatermarkRuntime", "Stop-WatermarkRuntime", "Toggle-WatermarkRuntime", "Resize-WindowForTaskRows", "Set-ActiveView", "Render-CurrentView", "Save-GeneralSettings", "Save-Settings", "Set-WatermarkDefaultTaskView", "TaskFontSize", "WatermarkPrevious")
    foreach ($translationStartupFile in @($translationRuntime, $translationCore, $translationBridge, $translationSelection)) { Test-FileDoesNotContain $translationStartupFile $translationHostLayoutTokens "$([System.IO.Path]::GetFileName($translationStartupFile)) must keep translation startup/tick paths free of host layout, view, font, and watermark lifecycle writes." }
    $platformRaw = Get-Content -LiteralPath $translationPlatform -Encoding UTF8 -Raw
    foreach ($required in @("function Ensure-TranslationPlatformTypes", "function Protect-TranslationSecret", "function Unprotect-TranslationSecret", "TaskPomodoroTranslationNative", "ProtectedData", '$script:TranslationPlatformTypesReady')) { if ($platformRaw -notlike "*$required*") { throw "TranslationPlatform.ps1 missing required marker: $required" } }
    Test-FileDoesNotContain $translationPlatform @("Invoke-RestMethod", "function Invoke-WatermarkTranslationApi", "function Show-WatermarkTranslationResult", "function Start-WatermarkTranslationMode", "function Ensure-WatermarkTranslationTypes", '$script:WatermarkTranslationTypesReady') "TranslationPlatform.ps1 must stay focused on neutral native type and secret helpers."
    $legacyPlatformRaw = Get-Content -LiteralPath $legacyTranslationPlatform -Encoding UTF8 -Raw
    foreach ($required in @("function Ensure-WatermarkTranslationTypes", "Ensure-TranslationPlatformTypes")) { if ($legacyPlatformRaw -notlike "*$required*") { throw "WatermarkTranslation.Platform.ps1 missing compatibility wrapper marker: $required" } }
    Test-FileDoesNotContain $legacyTranslationPlatform @("Add-Type -Language CSharp", "ProtectedData", "TaskPomodoroTranslationNative", "GetClipboardSequenceNumber", '$script:TranslationPlatformTypesReady', '$script:WatermarkTranslationTypesReady', "function Protect-TranslationSecret", "function Unprotect-TranslationSecret") "WatermarkTranslation.Platform.ps1 must stay compatibility-only; TranslationPlatform.ps1 owns native type and secret helpers."
    foreach ($neutralTranslationFile in @($translationRuntime, $translationSelection, $translationSurfaceFacade, $translationBridge)) { Test-FileDoesNotContain $neutralTranslationFile @("Ensure-WatermarkTranslationTypes") "$([System.IO.Path]::GetFileName($neutralTranslationFile)) must use Ensure-TranslationPlatformTypes instead of the historical platform wrapper." }
    $dictionaryRaw = Get-Content -LiteralPath $translationDictionary -Encoding UTF8 -Raw
    foreach ($required in @("function Get-TranslationBuiltinDictionaryPath", "function Convert-TranslationDefinitionToShortText", "function Clear-TranslationDictionaryCache", "function Add-TranslationDictionaryFile", "function Load-TranslationDictionary", "function Get-TranslationLookupCandidates", "function Get-TranslationLocalResult")) { if ($dictionaryRaw -notlike "*$required*") { throw "TranslationDictionary.ps1 missing required marker: $required" } }
    $legacyDictionaryRaw = Get-Content -LiteralPath $legacyTranslationDictionary -Encoding UTF8 -Raw; foreach ($required in @("function Get-WatermarkTranslationBuiltinDictionaryPath", "function Add-WatermarkTranslationDictionaryFile", "function Get-WatermarkTranslationLocalResult", "Get-TranslationLocalResult")) { if ($legacyDictionaryRaw -notlike "*$required*") { throw "WatermarkTranslation.Dictionary.ps1 missing compatibility wrapper marker: $required" } }
    Test-FileDoesNotContain $legacyTranslationDictionary @("[System.IO.File]::ReadLines", "`$script:TranslationDictionary", "Convert-TranslationDefinitionToShortText", "function Get-TranslationLocalResult", "function Load-TranslationDictionary ") "WatermarkTranslation.Dictionary.ps1 must stay compatibility-only; TranslationDictionary.ps1 owns local dictionary implementation."

    $surfaceRaw = Get-Content -LiteralPath $translationSurface -Encoding UTF8 -Raw
    foreach ($required in @("function Get-ScreenSafePoint", "function Set-WatermarkTranslationDetailLocation", "function Get-WatermarkTranslationFontSize", "function Ensure-WatermarkTranslationForms", "function Format-WatermarkTranslationDetail", "function Show-WatermarkTranslationResult", "function Hide-WatermarkTranslationResultFromTimer", "function Hide-WatermarkTranslationSurfaces", "function Dispose-WatermarkTranslationSurfaces", "Get-TranslationSurfaceSafePoint", "Set-TranslationSurfaceDetailLocation", "Get-TranslationSurfaceFontSize", "Ensure-TranslationSurfaceForms", "Format-TranslationSurfaceDetail", "Show-TranslationSurfaceResult", "Hide-TranslationSurfaces", "Dispose-TranslationSurfaces")) { if ($surfaceRaw -notlike "*$required*") { throw "WatermarkTranslation.Surface.ps1 missing compatibility wrapper marker: $required" } }
    Test-FileDoesNotContain $translationSurface @("TaskPomodoroNoActivateForm", "TaskPomodoroTranslationDetailForm", "FormBorderStyle", "Opacity", "Add_Tick", "New-Object System.Windows.Forms.Label", "WatermarkTranslationMiniLabel.Text", "Get-WatermarkTransparentColor", "Invoke-RestMethod", "function Invoke-WatermarkTranslationApi", "function Get-WatermarkTranslationSelection", "function Start-WatermarkTranslationClipboardListener", "Get-WatermarkTranslationLocalResult") "WatermarkTranslation.Surface.ps1 must stay compatibility-only; TranslationSurface.ps1 owns overlay rendering."
    $surfaceFacadeRaw = Get-Content -LiteralPath $translationSurfaceFacade -Encoding UTF8 -Raw; foreach ($required in @("function Get-TranslationSurfaceSafePoint", "function Set-TranslationSurfaceDetailLocation", "function Get-TranslationSurfaceFontSize", "function Ensure-TranslationSurfaceForms", "function Format-TranslationSurfaceDetail", "function Show-TranslationSurfaceResult", "function Hide-TranslationSurfaceResultFromTimer", "function Hide-TranslationSurfaces", "function Dispose-TranslationSurfaces", "TaskPomodoroNoActivateForm", "TaskPomodoroTranslationDetailForm", "Get-WatermarkTransparentColor")) { if ($surfaceFacadeRaw -notlike "*$required*") { throw "TranslationSurface.ps1 missing overlay implementation marker: $required" } }
    Test-FileDoesNotContain $translationSurfaceFacade @("Invoke-RestMethod", "function Invoke-WatermarkTranslationApi", "function Get-WatermarkTranslationSelection", "function Start-WatermarkTranslationClipboardListener", "Get-WatermarkTranslationLocalResult", "Resize-WindowForTaskRows", "Set-ActiveView", "Render-CurrentView", "TaskFontSize", "WatermarkPrevious", "`$script:WatermarkTranslationMiniForm", "`$script:WatermarkTranslationDetailForm", "`$script:WatermarkTranslationMiniLabel", "`$script:WatermarkTranslationDetailLabel", "`$script:WatermarkTranslationHideTimer") "TranslationSurface.ps1 must own overlay rendering without host layout, lookup side effects, or historical WatermarkTranslation* private surface state."
    $selectionRaw = Get-Content -LiteralPath $translationSelection -Encoding UTF8 -Raw; foreach ($required in @("function Get-TranslationSelection", "function Start-TranslationClipboardListener", "function Stop-TranslationClipboardListener", "function Update-TranslationClipboard")) { if ($selectionRaw -notlike "*$required*") { throw "TranslationSelection.ps1 missing required marker: $required" } }
    Test-FileDoesNotContain $translationSelection @("Set-Clipboard", "Clipboard]::SetText", "Clipboard]::SetDataObject", "SendKeys", "Invoke-TranslationWorkflowRequest", "Show-WatermarkTranslationText", "Show-TranslationText", "Show-TranslationSurfaceResult", "Hide-TranslationSurfaces", "Save-Settings") "TranslationSelection.ps1 may read selections and clipboard only; it must not write clipboard or call workflow/surface policy."

    $menuRaw = Get-Content -LiteralPath $watermarkMenu -Encoding UTF8 -Raw
    foreach ($required in @("function Add-WatermarkMenuAction", "function Show-WatermarkMenu", "ContextMenuStrip", "Start-TranslationRuntime", "Toggle-WatermarkRuntime", "Show-TranslationSettingsDialog")) {
        if ($menuRaw -notlike "*$required*") { throw "WatermarkMode.Menu.ps1 missing required marker: $required" }
    }
    Test-FileDoesNotContain $watermarkMenu @("Invoke-RestMethod", "Get-WatermarkTranslationLocalResult", "function Invoke-WatermarkTranslationApi", "function Ensure-WatermarkTranslationForms", "Start-WatermarkTranslationMode", "Stop-WatermarkTranslationMode", '$script:WatermarkTranslationMode', '$script:WatermarkTranslationSettingsDialog') "WatermarkMode.Menu.ps1 must use TranslationRuntime facade instead of translation implementation details."
    Test-FileDoesNotContain $watermarkMode @("Start-WatermarkTranslationMode", "Stop-WatermarkTranslationMode", "Start-TranslationRuntime", "Stop-TranslationRuntime", "Test-TranslationRuntimeActive", "Test-TranslationRuntimeTimerCreated", '$script:WatermarkTranslationMode') "WatermarkMode.ps1 must not own translation runtime lifecycle or implementation details."

}
