# This file is dot-sourced by Invoke-AutomatedChecks.ps1 for Pomodoro workflow boundary assertions.

function Invoke-PomodoroWorkflowBoundaryCheck([string]$ModulesDir) {
    $results = Join-Path $ModulesDir "PomodoroResults.ps1"
    $events = Join-Path $ModulesDir "PomodoroEvents.ps1"
    $eventSets = Join-Path $ModulesDir "PomodoroEventSets.ps1"
    $workflow = Join-Path $ModulesDir "PomodoroWorkflow.ps1"
    $timerView = Join-Path $ModulesDir "Views.Timer.ps1"
    $timerActions = Join-Path $ModulesDir "Views.Timer.Actions.ps1"
    $starterView = Join-Path $ModulesDir "Views.Timer.Starter.ps1"
    $taskMenuActions = Join-Path $ModulesDir "Views.Task.Menu.Actions.ps1"
    foreach ($requiredFile in @($results, $events, $eventSets, $workflow, $timerView, $timerActions, $starterView, $taskMenuActions)) { Test-RequiredFile $requiredFile }
    . (Join-Path $ModulesDir "ModuleLoadOrder.ps1"); $loadOrder = Get-TaskPomodoroModuleLoadOrder
    foreach ($moduleName in @("PomodoroResults.ps1", "PomodoroEvents.ps1", "PomodoroEventSets.ps1", "PomodoroEngine.ps1", "PomodoroStarter.ps1", "PomodoroWorkflow.ps1", "PomodoroRuntime.Queries.ps1", "Views.Timer.Actions.ps1", "Views.Timer.ps1", "Views.Timer.Starter.ps1", "Views.Task.Menu.Actions.ps1")) { if ([Array]::IndexOf($loadOrder, $moduleName) -lt 0) { throw "ModuleLoadOrder.ps1 missing $moduleName" } }
    foreach ($consumerModule in @("PomodoroEngine.ps1", "PomodoroStarter.ps1", "PomodoroWorkflow.ps1", "Views.Timer.Actions.ps1")) { if ([Array]::IndexOf($loadOrder, "PomodoroResults.ps1") -gt [Array]::IndexOf($loadOrder, $consumerModule)) { throw "PomodoroResults.ps1 must load before $consumerModule" } }
    foreach ($consumerModule in @("PomodoroEventSets.ps1", "PomodoroEngine.ps1", "PomodoroStarter.ps1", "PomodoroWorkflow.ps1", "Views.Timer.Starter.ps1")) { if ([Array]::IndexOf($loadOrder, "PomodoroEvents.ps1") -gt [Array]::IndexOf($loadOrder, $consumerModule)) { throw "PomodoroEvents.ps1 must load before $consumerModule" } }
    foreach ($consumerModule in @("PomodoroEngine.ps1")) { if ([Array]::IndexOf($loadOrder, "PomodoroEventSets.ps1") -gt [Array]::IndexOf($loadOrder, $consumerModule)) { throw "PomodoroEventSets.ps1 must load before $consumerModule" } }
    foreach ($sourceModule in @("PomodoroEngine.ps1", "PomodoroStarter.ps1", "TaskWorkflow.ps1")) { if ([Array]::IndexOf($loadOrder, $sourceModule) -gt [Array]::IndexOf($loadOrder, "PomodoroWorkflow.ps1")) { throw "PomodoroWorkflow.ps1 must load after $sourceModule" } }
    foreach ($viewModule in @("Views.Timer.Actions.ps1", "Views.Timer.ps1", "Views.Timer.Starter.ps1", "Views.Task.Menu.Actions.ps1")) { if ([Array]::IndexOf($loadOrder, "PomodoroWorkflow.ps1") -gt [Array]::IndexOf($loadOrder, $viewModule)) { throw "PomodoroWorkflow.ps1 must load before $viewModule" } }
    foreach ($dependent in @("UiTimer.ps1", "Views.Task.ps1", "Views.Task.Menu.Actions.ps1", "Views.Timer.Starter.ps1")) { if ([Array]::IndexOf($loadOrder, "Views.Timer.Actions.ps1") -gt [Array]::IndexOf($loadOrder, $dependent)) { throw "Views.Timer.Actions.ps1 must load before $dependent" } }
    $resultsRaw = Get-Content -LiteralPath $results -Encoding UTF8 -Raw
    foreach ($required in @("function New-PomodoroOperationResult", "ShouldUpdateTimer", "ShouldRender", 'Events = @($Events)')) { if ($resultsRaw -notlike "*$required*") { throw "PomodoroResults.ps1 missing operation result marker: $required" } }
    foreach ($stateMachineFile in @("PomodoroEngine.ps1", "PomodoroStarter.ps1")) { Test-FileDoesNotContain (Join-Path $ModulesDir $stateMachineFile) @("function New-PomodoroOperationResult") "$stateMachineFile must not own Pomodoro operation result shape." }
    $eventsRaw = Get-Content -LiteralPath $events -Encoding UTF8 -Raw
    foreach ($required in @("function New-PomodoroEvent", "function Add-PomodoroResultEvents", "function New-PomodoroAppendRecordEvent", "function New-PomodoroStartBackgroundAudioEvent", "function New-PomodoroStopBackgroundAudioEvent", "function New-PomodoroPlayStartSoundEvent", "function New-PomodoroTriggerReminderEvent", "function New-PomodoroIncrementTaskEvent", "function New-PomodoroInterruptedRecordEvent", "function New-PomodoroCompletedWorkRecordEvent", "function New-PomodoroCompletedBreakRecordEvent", "function Get-PomodoroElapsedSeconds", "New-AppEvent", "Add-AppResultEvents")) { if ($eventsRaw -notlike "*$required*") { throw "PomodoroEvents.ps1 missing event helper marker: $required" } }
    $eventSetsRaw = Get-Content -LiteralPath $eventSets -Encoding UTF8 -Raw
    foreach ($required in @("function New-PomodoroWorkStartedEvents", "function New-PomodoroPausedEvents", "function New-PomodoroResumedEvents", "function New-PomodoroIdleStoppedEvents", "function New-PomodoroInterruptedEvents", "function New-PomodoroWorkCompletedEvents", "function New-PomodoroBreakStartedEvents", "function New-PomodoroBreakCompletedEvents", "function New-PomodoroStarterStartedEvents", "function New-PomodoroStarterStoppedEvents", "function New-PomodoroStarterCompletedEvents", "pomodoro_paused", "pomodoro_resumed")) { if ($eventSetsRaw -notlike "*$required*") { throw "PomodoroEventSets.ps1 missing composite event helper marker: $required" } }
    $rawPomodoroEventTypes = @('"PlayStartSound"', '"StartBackgroundAudio"', '"StopBackgroundAudio"', '"TriggerReminder"', '"AppendPomodoroRecord"', '"IncrementTaskPomodoro"')
    foreach ($stateMachineFile in @("PomodoroEngine.ps1", "PomodoroStarter.ps1", "PomodoroWorkflow.ps1", "Views.Timer.Starter.ps1")) { Test-FileDoesNotContain (Join-Path $ModulesDir $stateMachineFile) $rawPomodoroEventTypes "$stateMachineFile must use PomodoroEvents.ps1 semantic event helpers instead of raw result-event type strings." }
    $rawPomodoroRecordResults = @('"skipped_break"', '"interrupted"', '"completed"', '"break_completed"', "New-PomodoroAppendRecordEvent", "StartedAtDate", "plannedSeconds")
    Test-FileDoesNotContain (Join-Path $ModulesDir "PomodoroEngine.ps1") $rawPomodoroRecordResults "PomodoroEngine.ps1 must use PomodoroEvents.ps1 record-event semantic helpers instead of constructing record event fields."
    Test-FileDoesNotContain (Join-Path $ModulesDir "PomodoroEngine.ps1") @("StartSoundReminder", "New-PomodoroPlayStartSoundEvent", "New-PomodoroStartBackgroundAudioEvent", "New-PomodoroStopBackgroundAudioEvent", "New-PomodoroTriggerReminderEvent", "New-PomodoroIncrementTaskEvent", "New-PomodoroInterruptedRecordEvent", "New-PomodoroCompletedWorkRecordEvent", "New-PomodoroCompletedBreakRecordEvent") "PomodoroEngine.ps1 must use PomodoroEvents.ps1 composite event helpers for state-transition side effects."
    Test-FileDoesNotContain (Join-Path $ModulesDir "PomodoroStarter.ps1") @("New-PomodoroStartBackgroundAudioEvent", "New-PomodoroStopBackgroundAudioEvent") "PomodoroStarter.ps1 must use PomodoroEventSets.ps1 composite event helpers for starter side effects."
    Test-FileDoesNotContain (Join-Path $ModulesDir "PomodoroEngine.ps1") @("function Clear-PomodoroTimerForTaskMutation", "Clear-PomodoroTimerForTaskMutation", "Get-PomodoroRuntimeCurrentTaskId") "PomodoroEngine.ps1 must not own task-mutation timer invalidation workflow."
    $workflowRaw = Get-Content -LiteralPath $workflow -Encoding UTF8 -Raw
    foreach ($required in @("function Invoke-PomodoroStartWorkflow", "Apply-PomodoroStartPlanIfNeeded", "function Invoke-PomodoroPauseOrContinueWorkflow", "function Invoke-PomodoroTaskInvalidationWorkflow", "function Invoke-PomodoroCompleteWorkflow", "Publish-AppNotification", "PomodoroFinished", "function Invoke-TaskStarterStartWorkflow", "function Get-TaskStarterCompletionDefaultAction", "StarterDefaultAction", "function Invoke-TaskStarterAgainWorkflow", "Test-PomodoroTaskNeedsAdditionalPlan", "Add-PomodoroEstimateForTask")) { if ($workflowRaw -notlike "*$required*") { throw "PomodoroWorkflow.ps1 missing required marker: $required" } }
    Test-FileDoesNotContain $workflow @("System.Windows.Forms", "MessageBox", "InputBox", "Set-Status", "Render-CurrentView", "Append-PomodoroRecord", "Play-StartSound", "Play-EndSound", "Start-BackgroundAudio", "Stop-BackgroundAudio", "Get-TaskById", "estimatedPomodoroCount", "Add-TaskEstimatedPomodoros", "Get-TaskRemainingPomodoros", "Test-TaskIsCompleted") "PomodoroWorkflow.ps1 must stay UI-free, avoid direct planning reads, and must not bypass existing Pomodoro result events."
    Test-FileDoesNotContain $workflow @('$script:TimerState', '$script:TimerPhase', '$script:CurrentPomodoroTaskId', '$script:CurrentPomodoroTaskTitle', '$script:PomodoroStartedAt') "PomodoroWorkflow.ps1 must use PomodoroRuntime.ps1 facade for runtime state reads."
    foreach ($required in @("Test-PomodoroRuntimeBreakPhase", "Get-PomodoroRuntimeCurrentTaskId", "Test-PomodoroRuntimePaused", "Test-PomodoroRuntimeRunning", "Get-PomodoroRuntimeCompletionNotificationSnapshot", "Invoke-PomodoroTaskInvalidationWorkflow")) { if ($workflowRaw -notlike "*$required*") { throw "PomodoroWorkflow.ps1 must keep runtime facade marker: $required" } }
    Test-FileDoesNotContain $timerView @("Start-PomodoroFromUi", "Complete-PomodoroFromUi", "Confirm-AdditionalPomodorosFromUi", "InputBox", "MessageBox") "Views.Timer.ps1 must keep timer rendering separate from Pomodoro UI action wrappers."
    Test-FileDoesNotContain $timerView @('$script:TimerState', '$script:TimerPhase', '$script:SecondsRemaining', '$script:CurrentPomodoroTaskId', '$script:CurrentPomodoroTaskTitle') "Views.Timer.ps1 must read Pomodoro runtime state through PomodoroRuntime.Queries.ps1 snapshots."
    $timerViewRaw = Get-Content -LiteralPath $timerView -Encoding UTF8 -Raw
    if ($timerViewRaw -notlike "*Get-PomodoroRuntimeTimerViewSnapshot*") { throw "Views.Timer.ps1 must use Get-PomodoroRuntimeTimerViewSnapshot for timer labels and button state." }
    $timerActionsRaw = Get-Content -LiteralPath $timerActions -Encoding UTF8 -Raw
    foreach ($required in @("function Start-PomodoroFromUi", "function Confirm-AdditionalPomodorosFromUi", "function Complete-PomodoroFromUi", "function Complete-PomodoroTickFromUi", "Invoke-PomodoroStartWorkflow", "Invoke-PomodoroCompleteWorkflow")) { if ($timerActionsRaw -notlike "*$required*") { throw "Views.Timer.Actions.ps1 missing required marker: $required" } }
    Test-FileDoesNotContain $timerActions @("function Render-TimerView", "function Update-TimerLabels", "TableLayoutPanel", "FlowLayoutPanel", "TimerLabel", "StartButton", "PauseButton", "(Start-Pomodoro ", "(Pause-Pomodoro", "(Continue-Pomodoro", "(Stop-Pomodoro", "(Complete-Pomodoro") "Views.Timer.Actions.ps1 must stay focused on UI action wrappers and must not render timer controls or call Pomodoro state machines directly."
    Test-FileDoesNotContain $timerActions @('$script:TimerState', '$script:TimerPhase') "Views.Timer.Actions.ps1 must read runtime state through PomodoroRuntime.Queries.ps1."
    foreach ($required in @("Test-PomodoroRuntimeIdle", "Test-PomodoroRuntimeStarterPhase")) { if ($timerActionsRaw -notlike "*$required*") { throw "Views.Timer.Actions.ps1 must keep runtime query facade marker: $required" } }
    Test-FileDoesNotContain $starterView @('$script:CurrentPomodoroTaskId', '$script:TimerState', '$script:TimerPhase') "Views.Timer.Starter.ps1 must read runtime state through PomodoroRuntime.Queries.ps1."
    $starterViewRaw = Get-Content -LiteralPath $starterView -Encoding UTF8 -Raw
    if ($starterViewRaw -notlike "*Get-PomodoroRuntimeCurrentTaskId*" -or $starterViewRaw -notlike "*Get-TaskStarterCompletionDefaultAction*") { throw "Views.Timer.Starter.ps1 must keep runtime current-task query and workflow default-action markers." }
    $directPomodoroOps = @("(Start-Pomodoro ", "(Pause-Pomodoro", "(Continue-Pomodoro", "(Stop-Pomodoro", "(Complete-Pomodoro", "(Start-TaskStarter ", "(Complete-TaskStarter")
    foreach ($viewFile in @($timerActions, $timerView, $starterView, $taskMenuActions)) { Test-FileDoesNotContain $viewFile $directPomodoroOps "$([System.IO.Path]::GetFileName($viewFile)) must use PomodoroWorkflow.ps1 for Pomodoro/starter mutations." }
    "Pomodoro UI mutations are routed through PomodoroWorkflow.ps1"
}
