# This file is dot-sourced by TaskPomodoro.ps1 and Invoke-AutomatedChecks.ps1.
function Get-TaskPomodoroSelfTestModuleLoadOrder {
    return @(
        "SelfTest.Support.ps1",
        "SelfTest.Tasks.ps1",
        "SelfTest.Configuration.ps1",
        "SelfTest.TaskLinks.ps1",
        "SelfTest.Pomodoro.ps1",
        "SelfTest.InboxExecution.ps1",
        "SelfTest.Ui.ps1",
        "SelfTest.ps1"
    )
}

function Get-TaskPomodoroModuleLoadOrder([bool]$IncludeSelfTest = $true) {
    $modules = @(
        "AppState.ps1",
        "UiText.ps1", "UiText.Execution.ps1",
        "Storage.ps1",
        "AudioCatalog.ps1",
        "SettingsSchema.ps1",
        "WindowStateCoordinator.ps1",
        "SettingsStore.ps1",
        "NotificationHub.ps1",
        "SettingsWorkflow.ps1",
        "TaskModel.ps1",
        "AppResultEvents.ps1",
        "BehaviorEvents.ps1",
        "PomodoroEvents.ps1",
        "PomodoroEventSets.ps1",
        "TaskStore.ps1",
        "InboxStore.ps1",
        "TaskQueries.ps1",
        "TaskOrdering.ps1",
        "TaskCommands.ps1", "TaskWorkflow.ps1", "InboxWorkflow.ps1",
        "TaskDetails.ps1",
        "TaskArchive.ps1",
        "DailyContinuity.ps1",
        "ExecutionRecords.ps1",
        "TaskFormat.ps1",
        "PomodoroRecords.ps1",
        "AudioPlayback.ps1",
        "PomodoroAudio.ps1",
        "PomodoroEffects.ps1",
        "PomodoroSession.ps1",
        "PomodoroPlanning.ps1",
        "PomodoroCoordinator.ps1",
        "PomodoroResults.ps1",
        "PomodoroFormat.ps1",
        "PomodoroEngine.ps1",
        "PomodoroInlineCountdown.ps1",
        "PomodoroStarter.ps1", "PomodoroWorkflow.ps1", "PomodoroRuntime.ps1", "PomodoroRuntime.Queries.ps1", "PomodoroRuntimeState.ps1",
        "AppRelaunch.ps1",
        "AppMaintenance.ps1",
        "WindowPlacement.ps1",
        "WindowChrome.ps1",
        "WindowSize.ps1",
        "WindowDrag.ps1",
        "WatermarkToggleButton.ps1", "WatermarkMode.ps1", "WatermarkRuntime.ps1",
        "DesktopShortcut.ps1",
        "Views.Timer.Actions.ps1",
        "UiTimer.ps1",
        "BottomChrome.ps1",
        "HelpSurface.ps1",
        "WatermarkGhostSurface.ps1",
        "TranslationPlatform.ps1", "WatermarkTranslation.Platform.ps1", "TranslationProviders.ps1",
        "TranslationDictionaryIndex.ps1", "TranslationDictionary.ps1", "TranslationDictionaryInstall.ps1", "WatermarkTranslation.Dictionary.ps1", "TranslationRules.ps1", "TranslationLookup.ps1",
        "TranslationSurface.ps1", "WatermarkTranslation.Surface.ps1", "TranslationSelection.ps1",
        "TranslationWorkflow.ps1", "TranslationBridge.ps1", "WatermarkTranslation.ps1",
        "TranslationRuntime.ps1",
        "WatermarkMode.Menu.ps1",
        "Views.Core.ps1",
        "Views.Task.Controls.ps1",
        "Views.Task.Gestures.ps1",
        "Views.Task.Interactions.ps1",
        "Views.Task.Items.ps1",
        "Views.Task.Hover.ps1",
        "Views.Task.ListDrawing.ps1",
        "Views.Task.Selection.ps1",
        "Views.Task.DetailsDialog.ps1",
        "Views.Task.Edit.ps1",
        "Views.Task.Events.ps1",
        "Views.Menu.Builders.ps1",
        "Views.Task.LinkMenu.ps1",
        "Views.Task.ps1",
        "Views.Task.Menu.Actions.ps1",
        "Views.Task.Menu.ps1",
        "Views.Inbox.ps1",
        "Views.Timer.ps1",
        "Views.Timer.Starter.ps1",
        "Views.Done.Stats.ps1", "Views.Done.Drawing.ps1", "Views.Done.ps1",
        "Views.More.ps1",
        "Views.Settings.Controls.ps1",
        "Views.Settings.General.ps1",
        "Views.Settings.Pomodoro.ps1",
        "TranslationSettings.ps1", "WatermarkTranslation.Settings.ps1",
        "Views.Settings.Starter.ps1",
        "Views.Settings.Apply.ps1",
        "Views.Timer.SettingsDialog.ps1",
        "Views.Settings.ps1"
    )
    if ($IncludeSelfTest) { $modules += @(Get-TaskPomodoroSelfTestModuleLoadOrder) }
    return $modules
}