# This file is dot-sourced by TaskPomodoro.ps1. Keep functions side-effect-light at load time.

$script:TextB64 = @{
    AppTitle = "5p6B566A5qGM6Z2i55Wq6IyE"
    TaskList = "5Lu75Yqh"
    TodayList = "5LuK5pel"
    Pomodoro = "55Wq6IyE"
    More = "5YW25a6D"
    Inbox = "5pS26ZuG"
    NoInboxItems = "5pqC5peg5pS26ZuG6aG5"
    InboxHint = "6L6T5YWl5paw5oOz5rOV5ZCO5oyJIEVudGVyIOaUtumbhu+8m+WPjOWHu+i9rOS4uuS7u+WKoQ=="
    InboxItemAdded = "5bey5Yqg5YWl5pS26ZuG566x"
    InboxItemDeleted = "5bey5Yig6Zmk5pS26ZuG6aG5"
    InboxItemPromoted = "5bey6L2s5Li65Lu75Yqh"
    InboxItemScheduled = "5bey5a6J5o6S5Yiw5LuK5pel"
    InboxItemEdited = "5bey5pu05paw5pS26ZuG6aG5"
    PromoteToTask = "6L2s5Li65Lu75Yqh"
    PromoteToToday = "5a6J5o6S5Yiw5LuK5pel"
    DailyContinuationTitle = "5o6l57ut5pio5pel5Lu75Yqh77yf"
    DailyContinuationSummary = "5pio5pel5a6M5oiQIHswfSDkuKrnlarojIQgLyDmgaLlpI3miJDlip8gezF9IOasoSAvIOaYqOaXpeacquWujOaIkCB7Mn0g6aG544CC5piv5ZCm5o6l57ut5pio5pel5Lu75Yqh77yf"
    SelectTodayTaskPrompt = "6K+36YCJ5oup5LuK5pel5Lu75Yqh"
    Close = "w5c="
    Today = "5LuK5aSp"
    InputHint = "6L6T5YWl5Lu75Yqh5ZCO5oyJ5Zue6L2m5paw5aKe"
    Add = "5paw5aKe"
    OpenTasks = "5pyq5a6M5oiQ5Lu75Yqh"
    TodayTasks = "5LuK5pel5Lu75Yqh"
    Done = "5bey57uT5p2f"
    Settings = "6K6+572u"
    DataCheck = "5pWw5o2u5qOA5p+l"
    StartPomodoro = "5ZCv5Yqo55Wq6IyE6ZKf"
    PomodoroMenu = "55Wq6IyE6ZKf"
    TaskStarterMenu = "5YWI5YGa"
    Complete = "5a6M5oiQ"
    CompleteTaskMenu = "5a6M5oiQ5Lu75Yqh"
    Cancel = "5Y+W5raI"
    ScheduleToday = "5a6J5o6S5Yiw5LuK5pel"
    RemoveFromToday = "5LuO5LuK5pel56e75Ye6"
    EndTask = "5b2S5qGj5Lu75Yqh"
    Edit = "57yW6L6R"
    Delete = "5Yig6Zmk"
    DeleteTask = "5Yig6Zmk5Lu75Yqh"
    DeleteTaskConfirm = "56Gu6K6k5Yig6Zmk6L+Z5Liq5Lu75Yqh77yf5q2k5pON5L2c5LiN6IO95pKk6ZSA44CC"
    PinToTop = "5Lu75Yqh572u6aG2"
    ReminderTime = "5pe26Ze05o+Q6YaS"
    DueDate = "5oiq5q2i5pe26Ze0"
    EditTask = "57yW6L6R5Lu75Yqh"
    TaskDetails = "5Lu75Yqh6K+m5oOF"
    TaskTitle = "5Lu75Yqh5qCH6aKY"
    TaskNotes = "5Lu75Yqh6K+05piO"
    TaskLinks = "6ZO+5o6lL+aWh+S7tg=="
    OpenTaskLink = "5omT5byA6ZO+5o6lL+aWh+S7tg=="
    NoTaskLink = "5rKh5pyJ5Y+v5omT5byA55qE6ZO+5o6l5oiW5paH5Lu2"
    EstimatedPomodoros = "6aKE6K6h55Wq6IyE5pWw"
    ActualPomodoros = "5a6e6ZmF55Wq6IyE5pWw"
    UncompleteTaskMenu = "5Y+W5raI5a6M5oiQ5Lu75Yqh"
    Help = "5biu5Yqp"
    HelpTitle = "55WM6Z2i6K+05piO"
    HelpQuick = "5b+r6YCf6K+05piO"
    HelpDiagram = "55WM6Z2i5Zu+56S6"
    HelpRules = "5pON5L2c6KeE5YiZ"
    HelpShortcuts = "5b+r5o236ZSu"
    HelpUpdate = "5pu05pawL+mHjeWQrw=="
    ShortcutF2EditTask = "RjIg57yW6L6R5Lu75Yqh"
    ShortcutCtrlDoubleClickOpenLink = "Q3RybCArIOWPjOWHu+aJk+W8gOmTvuaOpS/mlofku7Y="
    RestartApp = "6YeN5ZCv5b2T5YmN54mI5pys"
    OpenAppFolder = "5omT5byA6aG555uu55uu5b2V"
    UpdateFromGit = "5LuOIEdpdCDmm7TmlrDlubbph43lkK8="
    DesktopShortcutMenu = "5re75Yqg5qGM6Z2i5b+r5o235pa55byP"
    UpdateInfo = "5pu05paw6K+05piO"
    HelpSponsor = "5pSv5oyBL+i1nuWKqQ=="
    HelpAboutGovernance = "5YWz5LqOL+W8gOa6kOayu+eQhg=="
    HelpText = "5b+r6YCf5LiK5omL77yaCjEuIOmdoOi/keW6lemDqO+8jOaYvuekuuWvvOiIquWSjOi+k+WFpeahhu+8jOi+k+WFpeS7u+WKoeWQjuaMiSBFbnRlciDmlrDlop7jgIIKMi4g5Zyo5Lu75Yqh6aG15Y+M5Ye75Lu75Yqh77yM5a6J5o6S5Yiw5LuK5pel44CCCjMuIOWcqOS7iuaXpemhteWPjOWHu+S7u+WKoe+8jOWQr+WKqOeVquiMhOmSn+OAggoK5bi46KeE5pON5L2c77yaCuW3pumUrumAieaLqe+8m+WPs+mUruaJk+W8gOaTjeS9nOiPnOWNle+8m+aLluWKqOS7u+WKoeaOkuW6j++8m+avj+WkqeWHjOaZqOiHquWKqOW9kuaho+W3suWujOaIkOS7u+WKoeOAggoK6Jma5YyW77yaCueCueWHuyB+IOi/m+WFpeiZmuWMlu+8m+eCueWHuyDilrMg6YCA5Ye66Jma5YyW44CCCgrmm7TlpJror7TmmI7vvJoK54K55Ye7ID8g5p+l55yL55WM6Z2i5Zu+56S644CB5pON5L2c6KeE5YiZ44CB5b+r5o236ZSu44CB5pu05paw44CB5pSv5oyB5ZKM5rK755CG5L+h5oGv44CC"
    HelpDiagramText = "5Y+z5LiK6KeS77yaPyDluK7liqnvvIx+IOiZmuWMlu+8jOiZmuWMluS4rSDilrMg6YCA5Ye66Jma5YyW44CCDQrnrKzkuIDooYzkuIrmlrnvvJrmi5bliqjnqpflj6PjgIINCuS7u+WKoeihjO+8muW3pumUrumAieaLqe+8jOWPjOWHu+aJp+ihjOm7mOiupOWKqOS9nO+8jOWPs+mUruiPnOWNle+8jOmAieS4reWQjuWGjeasoeWNleWHu+WPr+e8lui+keagh+mimO+8jOaLluWKqOaOkuW6j+OAgg0K5bqV6YOo5Yy65Z+f77ya6Z2g6L+R5pe25pi+56S66L6T5YWl5qGG5ZKM5a+86Iiq77ybLSDmlLbotbfkuLrkuKTooYzvvIzilqEg5bGV5byA5Li65Y2B6KGM77yMWCDlhbPpl63jgII="
    HelpRulesText = "56m655m95aSE77ya5bem6ZSu5riF6Zmk6YCJ5oup44CCDQrku7vliqHovpPlhaXvvJrlj6/nlKgiMiDku7vliqEi5o+S5YWl5Yiw56ysIDIg5L2N77yb5peg5bqP5Y+36L+95Yqg5Yiw5pyr5bC+44CCDQrku7vliqHpobXvvJrlj4zlh7vlronmjpLliLDku4rml6XvvJvpgInkuK3lkI7lho3mrKHljZXlh7vlj6/nvJbovpHmoIfpopjjgIINCuS7iuaXpemhte+8muWPjOWHu+WQr+WKqOeVquiMhOmSn++8m+WPs+mUruWPr+eVquiMhOOAgeWFiOWBmiAzIOWIhumSn+OAgeWujOaIkOOAgee8lui+keaIluabtOWkmuOAguWFiOWBmiAzIOWIhumSn+S4jeiuoeWFpeeVquiMhO+8jOS5n+S4jeiHquWKqOWujOaIkOS7u+WKoeOAgg0K6Jma5YyW77ya5Y+q5L+d55WZIOKWsyDlj6/mk43kvZzvvIzlhbbkvZnngrnlh7vnqb/pgI/jgII="
    HelpShortcutsText = "RjLvvJrnvJbovpHpgInkuK3ku7vliqHjgIINCkN0cmwgKyDlj4zlh7vvvJrmiZPlvIDku7vliqHkuK3nmoTpk77mjqXmiJbmlofku7bjgII="
    UpdateInfoText = "5b2T5YmN55uu5b2V5rKh5pyJ5Y+v55So55qEIEdpdCDov5znq6/jgILml6XluLjmlLnliqjlkI7or7fpgInmi6nigJzph43lkK/lvZPliY3niYjmnKzigJ3jgILlj5HluIPnu5nku5bkurrkvb/nlKjml7bvvIzlj6/ku47mupDlpLTmiJbplZzlg4/kuIvovb3mlrDniYjlkI7opobnm5bnqIvluo/mlofku7bvvJtkYXRhIOWSjCBjb25maWcg55uu5b2V5L+d55WZ5Liq5Lq65pWw5o2u5LiO6K6+572u77yM5LiN5bqU6KaG55uW44CC"
    UpdateGitConfirm = "5bCG5YWz6Zet5b2T5YmN56qX5Y+j77yM5Zyo5ZCO5Y+w5omn6KGMIGdpdCBwdWxsIC0tZmYtb25see+8jOeEtuWQjumHjeWQr+eoi+W6j+OAguiLpeabtOaWsOWksei0pe+8jOivt+aJk+W8gOmhueebruebruW9leafpeeciyB1cGRhdGUubG9n44CC"
    UpdatingAndRestarting = "5q2j5Zyo5pu05paw5bm26YeN5ZCv"
    DesktopShortcutPromptTitle = "5re75Yqg5qGM6Z2i5b+r5o235pa55byP77yf"
    DesktopShortcutPromptBody = "5LiL5qyh5Y+v5Lul55u05o6l5LuO5qGM6Z2i5ZCv5Yqo77yM5LiN55So5YaN5omT5byA6Kej5Y6L55uu5b2V44CC"
    DesktopShortcutPromptHint = "5Y+q5Lya6K+i6Zeu5LiA5qyh77yb5L2g5Lmf5Y+v5Lul56iN5ZCO5Zyo5biu5Yqp6I+c5Y2V5Lit5re75Yqg44CC"
    DesktopShortcutAdd = "5re75Yqg"
    DesktopShortcutSkip = "5pqC5LiN"
    DesktopShortcutInstalled = "5bey5re75Yqg5qGM6Z2i5b+r5o235pa55byP"
    DesktopShortcutInstallFailed = "5b+r5o235pa55byP5re75Yqg5aSx6LSl"
    DesktopShortcutAlreadyExists = "5qGM6Z2i5b+r5o235pa55byP5bey5a2Y5Zyo"
    HelpSponsorText = "5p6B566A5qGM6Z2i55Wq6IyE5piv5YWN6LS55byA5rqQ6aG555uu44CC5b2T5YmN54mI5pys5LiN5YGa5bm/5ZGK44CB5LiN5by65Yi255m75b2V44CB5LiN5oqK5Z+656GA5Yqf6IO95pS+5YWl5LuY6LS55aKZ44CCYG7lpoLmnpzov5nkuKrlt6Xlhbflr7nkvaDmnInluK7liqnvvIzlj6/ku6XpgJrov4flj43ppojpl67popjjgIHmlLnov5vmlofmoaPjgIHliIbkuqvkvb/nlKjlu7rorq7miJbotZ7liqnmnaXmlK/mjIHmjIHnu63nu7TmiqTjgIJgbui1nuWKqeWFpeWPo+S/neaMgeS9jumike+8muWPquaUvuWcqOW4ruWKqeWPs+mUruiPnOWNle+8jOS4jei/m+WFpeS4u+a1geeoi++8jOS4jeWBmuW8ueeql+aPkOmGkuOAgg=="
    HelpAboutGovernanceText = "5pys5bel5YW35LyY5YWI5L+d5oyB5pys5Zyw44CB6L276YeP44CB5L2O5omT5omw44CCYG7lvIDmupDlrprkvY3vvJrln7rnoYDlip/og73lhY3otLnlj6/nlKjvvIzpobnnm67msrvnkIbpgI/mmI7vvIzlj5jmm7TlhYjor4TkvLDlho3lvIDlj5HjgIJgbuayu+eQhuWOn+WIme+8mueUqOaIt+aVsOaNrueVmeWcqOacrOWcsO+8m+WKn+iDvem7mOiupOWFi+WItu+8m+aWsOWinuWFpeWPo+WFiOivhOS8sOmikeeOh+WSjOW5suaJsOOAgg=="
    WatermarkToggle = "6L2s5o2i"
    WatermarkTranslation = "57+76K+R"
    TranslationSettings = "57+76K+R6K6+572u"
    TranslationStop = "5YGc5q2i57+76K+R"
    TranslationService = "57+76K+R5pyN5Yqh"
    TranslationTargetLanguage = "55uu5qCH6K+t6KiA"
    TranslationFontSize = "57+76K+R5a2X5Y+3"
    TranslationSurfaceStyle = "57+76K+R6IOM5pmv"
    TranslationSurfaceStyleFollow = "6Lef6ZqP6Jma5a6e54q25oCB"
    TranslationSurfaceColorMode = "57+76K+R6IOM5pmv6aKc6Imy5qih5byP"
    TranslationSurfaceColorModeBlackOnWhite = "6buR5a2X55m95bqV"
    TranslationSurfaceColorModeWhiteOnBlack = "55m95a2X6buR5bqV"
    TranslationSurfaceStyleBlur = "6Jma5YyW57+76K+R"
    TranslationSurfaceStyleSolid = "5a6e5YyW57+76K+R"
    TranslationMonthlyLimit = "5a2X56ym5LiK6ZmQL+aciA=="
    TranslationPerformanceMode = "57+76K+R5YaF5a2Y5qih5byP"
    TranslationModeFast = "5b+r6YCf57+76K+R"
    TranslationModeMemory = "6IqC57qm5YaF5a2Y5LyY5YWI77yI6buY6K6k77yJ"
    TranslationClipboardListener = "5Ymq6LS05p2/55uR5ZCs"
    TranslationClipboardListenerNote = "5Y+q55uR5ZCs55So5oi35aSN5Yi277yM5LiN5YaZ5YWl5Ymq6LS05p2/44CC"
    TranslationProviderCustom = "6Ieq5a6a5LmJ5o6l5Y+j"
    TranslationProviderBaidu = "55m+5bqm57+76K+R"
    TranslationEndpoint = "5o6l5Y+j5Zyw5Z2A"
    TranslationApiKey = "QVBJIOWvhumSpQ=="
    TranslationDeepLMode = "RGVlcEwg5qih5byP"
    TranslationBaiduAppId = "55m+5bqmIEFwcCBJRA=="
    TranslationBaiduSecret = "55m+5bqm5a+G6ZKl"
    TranslationTestConnection = "5rWL6K+V6L+e5o6l"
    TranslationApiGuide = "6YWN572u5pWZ56iL"
    TranslationImportDictionary = "5a+85YWl6K+N5YW4"
    TranslationUnbindDictionary = "6Kej57uR6K+N5YW4"
    TranslationGetFullDictionary = "6I635Y+W5a6M5pW054mI"
    TranslationDictionaryLoaded = "6K+N5YW45bey5Yqg6L29"
    TranslationDictionaryUnbound = "6K+N5YW45bey6Kej57uR"
    TranslationDictionaryUnavailable = "5pqC5pe25peg5rOV5Yqg6L296K+N5YW4"
    TranslationDictionaryDownloadHelp = "5LiL6L296K+05piO"
    TranslationDictionaryFull = "5a6M5pW06K+N5YW46K+05piO"
    TranslationPrivacyNote = "6buY6K6k5pys5Zyw5oyJ6ZyA57Si5byV5p+l6K+N77yM5LiN6IGU572R77yb6IqC57qm5YaF5a2Y5LyY5YWI5LuN5L+d55WZ6Ieq5Yqo5Y+W6K+N44CC6Ieq5Yqo5Y+W6K+N5Y+W5Yaz5LqO55uu5qCH6L2v5Lu255qEIFVJQSDmlK/mjIHvvIzor7vkuI3liLDml7blj6/lkK/nlKjliarotLTmnb/nm5HlkKzlhZzlupXjgIJBUEkga2V5IOivt+iHquihjOS/neWtmO+8jOacrOacuuWKoOWvhuS4jeetieS6juWPr+i3qOiuvuWkh+aBouWkjeOAgg=="
    TranslationSelectionUnread = "5pyq6K+75Yiw6YCJ5Yy6"
    TranslationLocalMiss = "5pys5Zyw5pyq5pS25b2V"
    TranslationServiceUnavailable = "57+76K+R5pyN5Yqh5LiN5Y+v55So"
    TranslationModeOn = "57+76K+R5qih5byP5bey5byA5ZCv"
    TranslationModeOff = "57+76K+R5qih5byP5bey5YWz6Zet"
    TranslationConnectionOk = "6L+e5o6l5Y+v55So"
    TranslationConnectionFailed = "6L+e5o6l5aSx6LSl"
    TranslationHelp = "6Jma5YyW57+76K+R6K+05piO"
    TranslationHelpText = "6Jma5YyW57+76K+R5byA5ZCv5ZCO77yM5Y+q5Zyo57+76K+R54q25oCB6K+75Y+W5b2T5YmN6YCJ5Yy677yb6IqC57qm5YaF5a2Y5qih5byP5L+d55WZ6Ieq5Yqo5Y+W6K+N77yM6YeH55So5oyJ6ZyA57Si5byV5p+l6K+N77yM5LiN5pW06KGo5Yqg6L295aSn6K+N5YW444CC6Ieq5Yqo5Y+W6K+N5L6d6LWW55uu5qCH6L2v5Lu255qEIFVJQSDpgInljLrmlK/mjIHvvJvlpoLmnpzor7vkuI3liLDpgInljLrvvIzor7flkK/nlKjliarotLTmnb/nm5HlkKzlubbmiYvliqjlpI3liLboi7HmlofmlofmnKzlhZzlupXjgILpu5jorqTkuI3oh6rliqjlpI3liLbjgIHkuI3lhpnlhaXliarotLTmnb/jgILlj6/pgInliarotLTmnb/nm5HlkKzlj6ror7vlj5bkvaDmiYvliqjlpI3liLbnmoToi7HmloflhoXlrrnvvIzkuI3mqKHmi58gQ3RybCtD77yM5LiN5Li05pe25aSN5Yi25oGi5aSN44CC5Y+q5pyJ5ZCv55So5bm26YWN572uIEFQSSDlkI7miY3lj5HpgIHpgInkuK3mlofmnKzjgII="
    TranslationDisabled = "56aB55So"
    TranslationDeepLFree = "RGVlcEwgRnJlZQ=="
    TranslationDeepLPro = "RGVlcEwgUHJv"
    Watermark = "6Jma5YyW"
    ExitWatermark = "6YCA5Ye66Jma5YyW"
    UnboundFocus = "5pyq57uR5a6a5LiT5rOo"
    Start = "5byA5aeL"
    Pause = "5pqC5YGc"
    Continue = "57un57ut"
    Stop = "5YGc5q2i"
    Reset = "6YeN572u"
    CurrentTask = "5b2T5YmN5Lu75Yqh"
    SaveSettings = "5L+d5a2Y6K6+572u"
    SoundReminder = "5o+Q56S66Z+z"
    StartSoundReminder = "5byA5aeL5o+Q56S66Z+z5LmQ"
    EndSoundReminder = "57uT5p2f5o+Q56S66Z+z"
    ColorReminder = "6aKc6Imy5o+Q6YaS"
    TaskbarReminder = "5Lu75Yqh5qCP6Zeq54OB"
    ToastReminder = "57O757uf6YCa55+l"
    DataOk = "5pWw5o2u5q2j5bi4"
    NoTasksFile = "5Lu75Yqh5pWw5o2u5paH5Lu25LiN5a2Y5Zyo77yM5bCG6Ieq5Yqo5Yib5bu644CC"
    PomodoroDone = "55Wq6IyE5a6M5oiQ"
    PomodoroLogged = "5bey6K6w5b2V55Wq6IyE44CC"
    PomodoroInterrupted = "55Wq6IyE5bey5Lit5pat"
    PomodoroPausedOverFive = "5pqC5YGc6LaF6L+H5LqU5YiG6ZKf77yM5omT5pat6K6h5pWwKzE="
    PomodoroPausedOverTen = "5pqC5YGc6LaF6L+H5Y2B5YiG6ZKf77yM5omT5pat6K6h5pWwKzE="
    StarterSettings = "56C05Yaw5ZCv5Yqo"
    StarterMinutes = "5YWI5YGa5pe26ZW/"
    StarterMusic = "5pyf6Ze06Z+z5LmQ"
    StarterDefaultAction = "57uT5p2f6buY6K6k"
    StarterFocusing = "56C05Yaw5ZCv5Yqo5Lit"
    StarterDone = "MyDliIbpkp/lt7LliLA="
    StarterDonePrompt = "5pe26Ze05Yiw5LqG77yM6KaB57un57ut5ZCX77yf"
    StarterAgain = "5YaN5YGa5LiA5qyh"
    StarterStartPomodoro = "5ZCv5Yqo55Wq6IyE6ZKf"
    StarterCompleteTask = "5a6M5oiQ5Lu75Yqh"
    StarterStop = "5YGc5q2i"
    StarterStopped = "MyDliIbpkp/lt7LlgZzmraI="
    PomodoroPlanPrompt = "6K+36L6T5YWl5pys5qyh6K6h5YiS55qE55Wq6IyE5pWw77ya"
    PomodoroPlanInvalid = "6K+36L6T5YWl5aSn5LqOIDAg55qE5pWw5a2X44CC"
    PomodoroAddPrompt = "5Lu75Yqh6L+Y5pyq5Yu+6YCJ5a6M5oiQ44CC6L+95Yqg5Yeg5Liq55Wq6IyE77yf55WZ56m65YiZ5LiN6L+95Yqg44CC"
    PomodoroAddInvalid = "6K+36L6T5YWl5aSn5LqOIDAg55qE6L+95Yqg5pWw6YeP44CC"
    ContinuousRounds = "6L+e57ut6L2u5qyh"
    AutoStartNextPomodoro = "6Ieq5Yqo57un57ut"
    ApplyThisPomodoro = "5LuF5pys5qyh"
    ApplyFuturePomodoros = "5pys5qyh5Y+K5ZCO57ut6buY6K6k"
    ReadyNextPomodoro = "5LiL5LiA6L2u5b6F5byA5aeL"
    RestoreDefaults = "5oGi5aSN6buY6K6k"
    TimerAlreadyRunning = "55Wq6IyE6ZKf5bey5Zyo6L+Q6KGM"
    Exit = "6YCA5Ye6"
    NoDoneTasks = "5rKh5pyJ5bey5a6M5oiQ5Lu75Yqh"
    CreatedAt = "5Yib5bu65pe26Ze0"
    CompletedAt = "5a6M5oiQ5pe26Ze0"
    PomodoroCount = "55Wq6IyE5pWw"
    NoTaskSelected = "5pyq6YCJ5oup5Lu75Yqh"
    EnterTaskFirst = "6K+35YWI6L6T5YWl5Lu75Yqh5YaF5a6544CC"
    WorkMinutes = "5bel5L2c5YiG6ZKf"
    ShortBreakMinutes = "5LyR5oGv5YiG6ZKf"
    Opacity = "5LiN6YCP5piO5bqm"
    TaskFontSize = "5Lu75Yqh5a2X5Y+3"
    TopMost = "572u6aG2"
    DataCheckDone = "5pWw5o2u5qOA5p+l5a6M5oiQ"
    TasksFileReadable = "5Lu75Yqh5paH5Lu25Y+v6K+75Y+W44CC"
    SettingsSaved = "6K6+572u5bey5L+d5a2Y"
    TaskAdded = "5Lu75Yqh5bey5re75Yqg"
    TaskCompleted = "5Lu75Yqh5bey5a6M5oiQ"
    TaskUncompleted = "5Lu75Yqh5bey5oGi5aSN"
    TaskDeleted = "5Lu75Yqh5bey5Yig6Zmk"
    DailyArchiveTime = "5q+P5pel57uT566X5pe26Ze0"
    DailyArchivedTasks = "5bey6Ieq5Yqo5b2S5qGj5a6M5oiQ5Lu75Yqh"
    ScheduledToday = "5bey5a6J5o6S5Yiw5LuK5pel"
    Focusing = "5LiT5rOo5Lit"
    NoOpenTasks = "5pqC5peg5Lu75Yqh"
    NoTodayTasks = "5LuK5pel5pqC5peg5Lu75Yqh"
    ClickTaskHint = "5Y+z6ZSu5Lu75Yqh5pON5L2c77yM5ouW5Yqo5o6S5bqP"
    Language = "6K+t6KiA"
    Chinese = "5Lit5paH"
    English = "6Iux5paH"
    GeneralSettings = "6YCa55So6K6+572u"
    PomodoroSettings = "55Wq6IyE6ZKf6K6+572u"
    AudioVolume = "6Z+z6YeP"
    WorkMusic = "5LiT5rOo6Z+z5LmQ"
    BreakMusic = "5LyR5oGv6Z+z5LmQ"
    WorkMusicLoop = "5LiT5rOo5b6q546v"
    BreakMusicLoop = "5LyR5oGv5b6q546v"
    Select = "6YCJ5oup"
    DefaultSettings = "6buY6K6k6K6+572u"
    AudioSelected = "5bey6YCJ5oup6Z+z6aKR"
    AudioFile = "6Z+z6aKR5paH5Lu2"
    LoopIcon = "4oa7"
    LoopOnIcon = "4oa7"
    LoopOffIcon = "4oqY"
    BreakFocusing = "5LyR5oGv5Lit"
    BreakDone = "5LyR5oGv57uT5p2f"
    AppAlreadyRunning = "5p6B566A5qGM6Z2i55Wq6IyE5bey57uP5Zyo6L+Q6KGM44CC"
}

$script:TextEn = @{
    AppTitle = "Minimal Desktop Pomodoro"
    TaskList = "Tasks"
    TodayList = "Today"
    Pomodoro = "Timer"
    More = "More"
    Inbox = "Inbox"
    NoInboxItems = "No inbox items"
    InboxHint = "Enter a new idea, then press Enter. Double click to promote to a task."
    InboxItemAdded = "Added to inbox"
    InboxItemDeleted = "Inbox item deleted"
    InboxItemPromoted = "Promoted to task"
    InboxItemScheduled = "Scheduled for today"
    InboxItemEdited = "Inbox item updated"
    PromoteToTask = "Promote to task"
    PromoteToToday = "Schedule today"
    DailyContinuationTitle = "Continue yesterday?"
    DailyContinuationSummary = "Yesterday completed {0} pomodoros / recovered {1} times / left {2} tasks unfinished. Continue yesterday tasks?"
    SelectTodayTaskPrompt = "Please choose today tasks"
    Close = "×"
    Today = "Today"
    InputHint = "Type a task, then press Enter"
    Add = "Add"
    OpenTasks = "Open tasks"
    TodayTasks = "Today"
    Done = "Done"
    Settings = "Settings"
    DataCheck = "Data check"
    StartPomodoro = "Start timer"
    PomodoroMenu = "Timer"
    TaskStarterMenu = "Starter"
    Complete = "Complete"
    CompleteTaskMenu = "Complete task"
    Cancel = "Cancel"
    ScheduleToday = "Schedule today"
    RemoveFromToday = "Remove from today"
    EndTask = "Archive task"
    Edit = "Edit"
    Delete = "Delete"
    DeleteTask = "Delete task"
    DeleteTaskConfirm = "Delete this task? This cannot be undone."
    PinToTop = "Pin to top"
    ReminderTime = "Reminder"
    DueDate = "Due date"
    EditTask = "Edit task"
    TaskDetails = "Task details"
    TaskTitle = "Task title"
    TaskNotes = "Task notes"
    TaskLinks = "Links / files"
    OpenTaskLink = "Open link / file"
    NoTaskLink = "No link or file to open"
    EstimatedPomodoros = "Estimated pomodoros"
    ActualPomodoros = "Actual pomodoros"
    UncompleteTaskMenu = "Mark not done"
    Help = "Help"
    HelpTitle = "UI help"
    HelpQuick = "Quick help"
    HelpDiagram = "Interface diagram"
    HelpRules = "Operation rules"
    HelpShortcuts = "Shortcuts"
    HelpUpdate = "Update / restart"
    ShortcutF2EditTask = "F2 edit task"
    ShortcutCtrlDoubleClickOpenLink = "Ctrl + double click link/file"
    RestartApp = "Restart current version"
    OpenAppFolder = "Open app folder"
    UpdateFromGit = "Update from Git and restart"
    DesktopShortcutMenu = "Add desktop shortcut"
    UpdateInfo = "Update info"
    HelpSponsor = "Support / sponsor"
    HelpAboutGovernance = "About / open-source governance"
    HelpText = "Quick start:`n1. Move near the bottom to show navigation and the input box, then type a task and press Enter.`n2. In Tasks, double click a task to schedule it for Today.`n3. In Today, double click a task to start a timer.`n`nCommon actions:`nLeft click selects; right click opens actions; drag tasks to reorder; completed tasks are archived automatically every midnight.`n`nBlur:`nClick ~ to enter blur mode; click △ to exit blur.`n`nMore help:`nClick ? for interface diagram, operation rules, shortcuts, update, support, and governance."
    HelpDiagramText = "Top right: ? help, ~ blur, triangle exits blur.`nFirst-row top band: drag the window.`nTask row: left click selects, double click runs the default action, right click opens actions, click a selected task again to edit its title, drag to reorder.`nBottom area: move near it to show input and navigation; - collapses to two rows, square expands to ten rows, X closes."
    HelpRulesText = "Blank area: left click clears selection.`nTask input: type '2 task' to insert at position 2; no number appends to the end.`nTasks view: double click schedules to Today; click a selected task again to edit its title.`nToday view: double click starts a timer; right click offers timer, start 3 min, complete, edit, and more. Start 3 min does not count as a pomodoro or complete the task automatically.`nBlur: only the triangle is interactive; other clicks pass through."
    HelpShortcutsText = "F2: edit the selected task.`nCtrl + double click: open the task link/file."
    UpdateInfoText = "No Git remote is configured for this folder. After local edits, choose Restart current version. For distributed copies, download the latest version from the source or mirror and replace the program files; keep data and config to preserve personal data and settings."
    UpdateGitConfirm = "The app will close, run git pull --ff-only in the background, then restart. If it fails, open the app folder and check update.log."
    UpdatingAndRestarting = "Updating and restarting"
    DesktopShortcutPromptTitle = "Add desktop shortcut?"
    DesktopShortcutPromptBody = "Start from the desktop next time without opening the extracted folder."
    DesktopShortcutPromptHint = "Asked once; you can add it later from the Help menu."
    DesktopShortcutAdd = "Add"
    DesktopShortcutSkip = "Not now"
    DesktopShortcutInstalled = "Desktop shortcut added"
    DesktopShortcutInstallFailed = "Desktop shortcut failed"
    DesktopShortcutAlreadyExists = "Desktop shortcut already exists"
    HelpSponsorText = "Minimal Desktop Pomodoro is a free and open-source project. This version has no ads, no forced login, and no paywall for basic features.`nIf this tool helps you, you can support maintenance by reporting issues, improving docs, sharing usage feedback, or sponsoring.`nThe sponsor path stays low frequency: it only appears in the Help right-click menu, never in the main workflow, and never as a popup reminder."
    HelpAboutGovernanceText = "This tool prioritizes local data, light weight, and low interruption.`nOpen-source positioning: basic features stay free, governance stays transparent, and changes are evaluated before implementation.`nGovernance principles: user data stays local; features are restrained by default; new entry points are evaluated for frequency and distraction."
    WatermarkToggle = "Switch"
    WatermarkTranslation = "Translate"
    TranslationSettings = "Translation settings"
    TranslationStop = "Stop translation"
    TranslationService = "Translation service"
    TranslationTargetLanguage = "Target language"
    TranslationFontSize = "Translation font size"
    TranslationSurfaceStyle = "Translation background"
    TranslationSurfaceStyleFollow = "Follow blur state"
    TranslationSurfaceColorMode = "Translation surface color mode"
    TranslationSurfaceColorModeBlackOnWhite = "Black text, white background"
    TranslationSurfaceColorModeWhiteOnBlack = "White text, black background"
    TranslationSurfaceStyleBlur = "Blur translation"
    TranslationSurfaceStyleSolid = "Solid translation"
    TranslationMonthlyLimit = "Chars / month"
    TranslationPerformanceMode = "Translation memory mode"
    TranslationModeFast = "Fast translation"
    TranslationModeMemory = "Memory saver (default)"
    TranslationClipboardListener = "Clipboard listener"
    TranslationClipboardListenerNote = "Only listens to text you copy; it never writes to the clipboard."
    TranslationProviderCustom = "Custom endpoint"
    TranslationProviderBaidu = "Baidu Translate"
    TranslationEndpoint = "Endpoint URL"
    TranslationApiKey = "API key"
    TranslationDeepLMode = "DeepL mode"
    TranslationBaiduAppId = "Baidu App ID"
    TranslationBaiduSecret = "Baidu secret"
    TranslationTestConnection = "Test"
    TranslationApiGuide = "Setup guide"
    TranslationImportDictionary = "Import dictionary"
    TranslationUnbindDictionary = "Unbind dictionary"
    TranslationGetFullDictionary = "Get full"
    TranslationDictionaryLoaded = "Dictionary loaded"
    TranslationDictionaryUnbound = "Dictionary unbound"
    TranslationDictionaryUnavailable = "Dictionary unavailable"
    TranslationDictionaryDownloadHelp = "Download help"
    TranslationDictionaryFull = "Full dictionary"
    TranslationPrivacyNote = "Default local lookup uses an on-demand index and stays offline. Memory saver keeps automatic selection enabled. Automatic selection depends on the target app's UIA support; use the clipboard listener when selection is unreadable. Save API keys yourself; local encryption cannot restore them on another device."
    TranslationSelectionUnread = "Selection not readable"
    TranslationLocalMiss = "Not in local dictionary"
    TranslationServiceUnavailable = "Translation service unavailable"
    TranslationModeOn = "Translation mode on"
    TranslationModeOff = "Translation mode off"
    TranslationConnectionOk = "Connection OK"
    TranslationConnectionFailed = "Connection failed"
    TranslationHelp = "Blur translation help"
    TranslationHelpText = "Blur translation reads the current selection only while translation mode is active. Memory saver keeps automatic selection enabled and uses on-demand indexed dictionary lookup instead of loading the full dictionary. Automatic selection depends on the target app's UIA selection support; if selection is unreadable, enable the clipboard listener and manually copy English text as the fallback. By default it does not copy automatically or write the clipboard. The optional clipboard listener only reads English text you manually copy; it never simulates Ctrl+C or performs copy-restore. Selected text is sent only after you enable and configure an API."
    TranslationDisabled = "Disabled"
    TranslationDeepLFree = "DeepL Free"
    TranslationDeepLPro = "DeepL Pro"
    Watermark = "Blur"
    ExitWatermark = "Exit blur"
    UnboundFocus = "Unbound focus"
    Start = "Start"
    Pause = "Pause"
    Continue = "Continue"
    Stop = "Stop"
    Reset = "Reset"
    CurrentTask = "Current task"
    SaveSettings = "Save"
    SoundReminder = "Sound"
    StartSoundReminder = "Start sound"
    EndSoundReminder = "End sound"
    ColorReminder = "Color cue"
    TaskbarReminder = "Taskbar flash"
    ToastReminder = "System notification"
    DataOk = "Data OK"
    NoTasksFile = "Task data file missing. It will be created."
    PomodoroDone = "Timer done"
    PomodoroLogged = "Timer logged."
    PomodoroInterrupted = "Timer interrupted"
    PomodoroPausedOverFive = "Paused over 5 minutes. Interruption count +1"
    PomodoroPausedOverTen = "Paused over 10 minutes. Interruption count +1"
    StarterSettings = "Starter"
    StarterMinutes = "Starter min"
    StarterMusic = "Starter music"
    StarterDefaultAction = "After default"
    StarterFocusing = "Starter running"
    StarterDone = "3 min done"
    StarterDonePrompt = "3 minutes are up. Continue?"
    StarterAgain = "Another round"
    StarterStartPomodoro = "Start timer"
    StarterCompleteTask = "Complete task"
    StarterStop = "Stop"
    StarterStopped = "3 min stopped"
    PomodoroPlanPrompt = "Planned pomodoros for this task:"
    PomodoroPlanInvalid = "Enter a number greater than 0."
    PomodoroAddPrompt = "Task is not marked done. Add how many more pomodoros? Leave blank to stop."
    PomodoroAddInvalid = "Enter an additional count greater than 0."
    ContinuousRounds = "Rounds"
    AutoStartNextPomodoro = "Auto continue"
    ApplyThisPomodoro = "This session"
    ApplyFuturePomodoros = "This and future defaults"
    ReadyNextPomodoro = "Next round ready"
    RestoreDefaults = "Restore defaults"
    TimerAlreadyRunning = "Timer is already running."
    Exit = "Exit"
    NoDoneTasks = "No completed tasks"
    CreatedAt = "Created"
    CompletedAt = "Completed"
    PomodoroCount = "Pomodoros"
    NoTaskSelected = "No task selected"
    EnterTaskFirst = "Enter a task first."
    WorkMinutes = "Work min"
    ShortBreakMinutes = "Break min"
    Opacity = "Opacity"
    TaskFontSize = "Task font size"
    TopMost = "Topmost"
    DataCheckDone = "Data check done"
    TasksFileReadable = "Task file is readable."
    SettingsSaved = "Settings saved"
    TaskAdded = "Task added"
    TaskCompleted = "Task completed"
    TaskUncompleted = "Task restored"
    TaskDeleted = "Task deleted"
    DailyArchiveTime = "Daily settlement"
    DailyArchivedTasks = "Completed tasks archived"
    ScheduledToday = "Scheduled today"
    Focusing = "Focusing"
    NoOpenTasks = "No tasks"
    NoTodayTasks = "No today tasks"
    ClickTaskHint = "Right-click tasks; drag to reorder"
    Language = "Language"
    Chinese = "Chinese"
    English = "English"
    GeneralSettings = "General"
    PomodoroSettings = "Pomodoro"
    AudioVolume = "Volume"
    WorkMusic = "Focus music"
    BreakMusic = "Break music"
    WorkMusicLoop = "Focus loop"
    BreakMusicLoop = "Break loop"
    Select = "Select"
    DefaultSettings = "Defaults"
    AudioSelected = "Audio selected"
    AudioFile = "Audio file"
    LoopIcon = "4oa7"
    BreakFocusing = "On break"
    BreakDone = "Break done"
    AppAlreadyRunning = "Minimal Desktop Pomodoro is already running."
}

function Get-DefaultLanguage([string]$CultureName = "") {
    if ([string]::IsNullOrWhiteSpace($CultureName)) {
        $CultureName = [System.Globalization.CultureInfo]::CurrentUICulture.Name
    }
    if (-not [string]::IsNullOrWhiteSpace($CultureName) -and $CultureName.StartsWith("zh", [System.StringComparison]::OrdinalIgnoreCase)) {
        return "zh-CN"
    }
    return "en-US"
}

function T([string]$Key) {
    if ($Key -in @("LoopIcon", "LoopOnIcon", "LoopOffIcon")) {
        return [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($script:TextB64[$Key]))
    }
    $language = Get-DefaultLanguage
    if ($null -ne $script:Settings -and ($script:Settings.PSObject.Properties.Name -contains "Language")) {
        $language = [string]$script:Settings.Language
    }
    if ($language -eq "en-US" -and $script:TextEn.ContainsKey($Key)) {
        return $script:TextEn[$Key]
    }
    return [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($script:TextB64[$Key]))
}
