# This file is dot-sourced by TaskPomodoro.ps1. Keep functions side-effect-light at load time.

$script:TextB64 = @{
    AppTitle = "5p6B566A5qGM6Z2i55Wq6IyE"
    TaskList = "5Lu75Yqh"
    TodayList = "5LuK5pel"
    Pomodoro = "55Wq6IyE"
    More = "5YW25a6D"
    Close = "w5c="
    Today = "5LuK5aSp"
    InputHint = "6L6T5YWl5Lu75Yqh5ZCO5oyJ5Zue6L2m5paw5aKe"
    Add = "5paw5aKe"
    OpenTasks = "5pyq5a6M5oiQ5Lu75Yqh"
    TodayTasks = "5LuK5pel5Lu75Yqh"
    Done = "5bey57uT5p2f"
    Settings = "6K6+572u"
    DataCheck = "5pWw5o2u5qOA5p+l"
    StartPomodoro = "5ZCv5Yqo55Wq6IyE6ZKf"
    PomodoroMenu = "55Wq6IyE6ZKf"
    Complete = "5a6M5oiQ"
    CompleteTaskMenu = "5a6M5oiQ5Lu75Yqh"
    Cancel = "5Y+W5raI"
    ScheduleToday = "5a6J5o6S5Yiw5LuK5pel"
    RemoveFromToday = "5LuO5LuK5pel56e75Ye6"
    EndTask = "5b2S5qGj5Lu75Yqh"
    PinToTop = "5Lu75Yqh572u6aG2"
    ReminderTime = "5pe26Ze05o+Q6YaS"
    DueDate = "5oiq5q2i5pe26Ze0"
    EditTask = "57yW6L6R5Lu75Yqh"
    TaskDetails = "5Lu75Yqh6K+m5oOF"
    TaskTitle = "5Lu75Yqh5qCH6aKY"
    TaskNotes = "5Lu75Yqh6K+05piO"
    TaskLinks = "6ZO+5o6lL+aWh+S7tg=="
    OpenTaskLink = "5omT5byA6ZO+5o6lL+aWh+S7tg=="
    NoTaskLink = "5rKh5pyJ5Y+v5omT5byA55qE6ZO+5o6l5oiW5paH5Lu2"
    EstimatedPomodoros = "6aKE6K6h55Wq6IyE5pWw"
    ActualPomodoros = "5a6e6ZmF55Wq6IyE5pWw"
    UncompleteTaskMenu = "5Y+W5raI5a6M5oiQ5Lu75Yqh"
    Help = "5biu5Yqp"
    HelpTitle = "55WM6Z2i6K+05piO"
    HelpQuick = "5b+r6YCf6K+05piO"
    HelpDiagram = "55WM6Z2i5Zu+56S6"
    HelpRules = "5pON5L2c6KeE5YiZ"
    HelpShortcuts = "5b+r5o236ZSu"
    HelpUpdate = "5pu05pawL+mHjeWQrw=="
    RestartApp = "6YeN5ZCv5b2T5YmN54mI5pys"
    OpenAppFolder = "5omT5byA6aG555uu55uu5b2V"
    UpdateFromGit = "5LuOIEdpdCDmm7TmlrDlubbph43lkK8="
    DesktopShortcutMenu = "5re75Yqg5qGM6Z2i5b+r5o235pa55byP"
    UpdateInfo = "5pu05paw6K+05piO"
    HelpSponsor = "5pSv5oyBL+i1nuWKqQ=="
    HelpAboutGovernance = "5YWz5LqOL+W8gOa6kOayu+eQhg=="
    HelpText = "5Lu75YqhL+S7iuaXpe+8muW3pumUrumAieaLqe+8jOWPjOWHu+aJp+ihjOm7mOiupOWKqOS9nO+8jOWPs+mUruaJk+W8gOaTjeS9nOiPnOWNle+8jOaLluWKqOaOkuW6j+OAggrnqpflj6PvvJrnrKzkuIDooYzkuIrmlrnljLrln5/lj6/mi5bliqjnqpflj6PvvIzovrnnvJjlj6/osIPmlbTlpKflsI/vvJvlupXpg6jpnaDov5Hml7bmmL7npLrovpPlhaXmoYblkozlr7zoiKrjgIIK5rC05Y2w77ya54K55Ye7IH4g6L+b5YWl5Y2K6YCP5piO572u6aG25o+Q6YaS77yb5rC05Y2w54q25oCB5LiL77yM6Zmk5Y+z5LiK6KeSIOKWsyDlpJbvvIzngrnlh7vkvJrnqb/pgI/liLDkuIvpnaLnqpflj6PvvJvngrkg4pazIOmAgOWHuuawtOWNsOOAggrlv6vmjbfplK7vvJrovpPlhaXmoYYgRW50ZXIg5paw5aKe77yb5Lu75Yqh5YiX6KGoIEYyIOe8lui+keagh+mimO+8m0N0cmwr5Y+M5Ye75omT5byA6ZO+5o6lL+aWh+S7tu+8m+agh+mimOe8lui+keS4rSBFbnRlciDkv53lrZjjgIFFc2Mg5Y+W5raI44CCCuW4ruWKqe+8muW3pumUriA/IOafpeeci+W/q+mAn+ivtOaYju+8jOWPs+mUriA/IOafpeeci+WbvuekuuOAgeinhOWImeOAgeW/q+aNt+mUruOAgeaUr+aMgeWSjOayu+eQhuS/oeaBr+OAggrnlarojITvvJrku47ku4rml6Xku7vliqHmiJbnlarojITpobXlkK/liqjvvIzmmoLlgZzlkI7mjInpkq7kvJrlj5jkuLrnu6fnu63jgII="
    HelpDiagramText = "5Y+z5LiK6KeS77yaPyDluK7liqnvvIx+IOawtOWNsO+8jOawtOWNsOS4rSDilrMg6YCA5Ye644CCCuesrOS4gOihjOS4iuaWue+8muaLluWKqOeql+WPo+OAggrku7vliqHooYzvvJrlt6bplK7pgInmi6nvvIzlj4zlh7vpu5jorqTliqjkvZzvvIzlj7PplK7oj5zljZXvvIxGMiDnvJbovpHmoIfpopjvvIzmi5bliqjmjpLluo/jgIIK5bqV6YOo5Yy65Z+f77ya6Z2g6L+R5pe25pi+56S66L6T5YWl5qCP5ZKM5a+86Iiq77ybLSDmlLbotbfkuLrkuIDooYzvvIzilqEg5bGV5byA5Li65Y2B6KGM77yMWCDlhbPpl63jgII="
    HelpRulesText = "56m655m95aSE77ya5bem6ZSu5riF6Zmk6YCJ5oup44CCCuS7u+WKoei+k+WFpe+8muWPr+eUqOKAnDIg5Lu75Yqh4oCd5o+S5YWl5Yiw56ysIDIg5L2N77yb5peg5bqP5Y+36L+95Yqg5Yiw5pyr5bC+44CCCuS7u+WKoemhte+8muWPjOWHu+WuieaOkuWIsOS7iuaXpe+8m+mAieS4reWQjuWGjeasoeWNleWHu+aIliBGMiDlj6/nvJbovpHmoIfpopjjgIIK5LuK5pel6aG177ya5Y+M5Ye75ZCv5Yqo55Wq6IyE77yb5Y+z6ZSu5Y+v55Wq6IyE44CB5a6M5oiQ44CB57yW6L6R5oiW5pu05aSa44CCCuawtOWNsO+8muWPquS/neeVmSDilrMg5Y+v5pON5L2c77yM5YW25L2Z54K55Ye756m/6YCP44CC"
    HelpShortcutsText = "6L6T5YWl5qGG77yaRW50ZXIg5paw5aKe5Lu75Yqh44CCCuS7u+WKoeWIl+ihqO+8mkYyIOe8lui+kemAieS4reS7u+WKoeagh+mimO+8m+WPjOWHu+aJp+ihjOm7mOiupOWKqOS9nO+8m0N0cmwr5Y+M5Ye75omT5byA6ZO+5o6lL+aWh+S7tuOAggrmoIfpopjnvJbovpHvvJpFbnRlciDkv53lrZjvvIxFc2Mg5Y+W5raI44CC"
    UpdateInfoText = "5b2T5YmN55uu5b2V5rKh5pyJ5Y+v55So55qEIEdpdCDov5znq6/jgILml6XluLjmlLnliqjlkI7or7fpgInmi6nigJzph43lkK/lvZPliY3niYjmnKzigJ3jgILlj5HluIPnu5nku5bkurrkvb/nlKjml7bvvIzlj6/ku47mupDlpLTmiJbplZzlg4/kuIvovb3mlrDniYjlkI7opobnm5bnqIvluo/mlofku7bvvJtkYXRhIOWSjCBjb25maWcg55uu5b2V5L+d55WZ5Liq5Lq65pWw5o2u5LiO6K6+572u77yM5LiN5bqU6KaG55uW44CC"
    UpdateGitConfirm = "5bCG5YWz6Zet5b2T5YmN56qX5Y+j77yM5Zyo5ZCO5Y+w5omn6KGMIGdpdCBwdWxsIC0tZmYtb25see+8jOeEtuWQjumHjeWQr+eoi+W6j+OAguiLpeabtOaWsOWksei0pe+8jOivt+aJk+W8gOmhueebruebruW9leafpeeciyB1cGRhdGUubG9n44CC"
    UpdatingAndRestarting = "5q2j5Zyo5pu05paw5bm26YeN5ZCv"
    DesktopShortcutPromptTitle = "5re75Yqg5qGM6Z2i5b+r5o235pa55byP77yf"
    DesktopShortcutPromptBody = "5LiL5qyh5Y+v5Lul55u05o6l5LuO5qGM6Z2i5ZCv5Yqo77yM5LiN55So5YaN5omT5byA6Kej5Y6L55uu5b2V44CC"
    DesktopShortcutPromptHint = "5Y+q5Lya6K+i6Zeu5LiA5qyh77yb5L2g5Lmf5Y+v5Lul56iN5ZCO5Zyo5biu5Yqp6I+c5Y2V5Lit5re75Yqg44CC"
    DesktopShortcutAdd = "5re75Yqg"
    DesktopShortcutSkip = "5pqC5LiN"
    DesktopShortcutInstalled = "5bey5re75Yqg5qGM6Z2i5b+r5o235pa55byP"
    DesktopShortcutInstallFailed = "5b+r5o235pa55byP5re75Yqg5aSx6LSl"
    DesktopShortcutAlreadyExists = "5qGM6Z2i5b+r5o235pa55byP5bey5a2Y5Zyo"
    HelpSponsorText = "5p6B566A5qGM6Z2i55Wq6IyE5piv5YWN6LS55byA5rqQ6aG555uu44CC5b2T5YmN54mI5pys5LiN5YGa5bm/5ZGK44CB5LiN5by65Yi255m75b2V44CB5LiN5oqK5Z+656GA5Yqf6IO95pS+5YWl5LuY6LS55aKZ44CCYG7lpoLmnpzov5nkuKrlt6Xlhbflr7nkvaDmnInluK7liqnvvIzlj6/ku6XpgJrov4flj43ppojpl67popjjgIHmlLnov5vmlofmoaPjgIHliIbkuqvkvb/nlKjlu7rorq7miJbotZ7liqnmnaXmlK/mjIHmjIHnu63nu7TmiqTjgIJgbui1nuWKqeWFpeWPo+S/neaMgeS9jumike+8muWPquaUvuWcqOW4ruWKqeWPs+mUruiPnOWNle+8jOS4jei/m+WFpeS4u+a1geeoi++8jOS4jeWBmuW8ueeql+aPkOmGkuOAgg=="
    HelpAboutGovernanceText = "5pys5bel5YW35LyY5YWI5L+d5oyB5pys5Zyw44CB6L276YeP44CB5L2O5omT5omw44CCYG7lvIDmupDlrprkvY3vvJrln7rnoYDlip/og73lhY3otLnlj6/nlKjvvIzpobnnm67msrvnkIbpgI/mmI7vvIzlj5jmm7TlhYjor4TkvLDlho3lvIDlj5HjgIJgbuayu+eQhuWOn+WIme+8mueUqOaIt+aVsOaNrueVmeWcqOacrOWcsO+8m+WKn+iDvem7mOiupOWFi+WItu+8m+aWsOWinuWFpeWPo+WFiOivhOS8sOmikeeOh+WSjOW5suaJsOOAgg=="
    Watermark = "5rC05Y2w"
    ExitWatermark = "6YCA5Ye65rC05Y2w"
    UnboundFocus = "5pyq57uR5a6a5LiT5rOo"
    Start = "5byA5aeL"
    Pause = "5pqC5YGc"
    Continue = "57un57ut"
    Stop = "5YGc5q2i"
    Reset = "6YeN572u"
    CurrentTask = "5b2T5YmN5Lu75Yqh"
    SaveSettings = "5L+d5a2Y6K6+572u"
    SoundReminder = "5o+Q56S66Z+z"
    StartSoundReminder = "5byA5aeL5o+Q56S66Z+z5LmQ"
    EndSoundReminder = "57uT5p2f5o+Q56S66Z+z"
    ColorReminder = "6aKc6Imy5o+Q6YaS"
    TaskbarReminder = "5Lu75Yqh5qCP6Zeq54OB"
    ToastReminder = "57O757uf6YCa55+l"
    DataOk = "5pWw5o2u5q2j5bi4"
    NoTasksFile = "5Lu75Yqh5pWw5o2u5paH5Lu25LiN5a2Y5Zyo77yM5bCG6Ieq5Yqo5Yib5bu644CC"
    PomodoroDone = "55Wq6IyE5a6M5oiQ"
    PomodoroLogged = "5bey6K6w5b2V55Wq6IyE44CC"
    PomodoroInterrupted = "55Wq6IyE5bey5Lit5pat"
    TimerAlreadyRunning = "55Wq6IyE6ZKf5bey5Zyo6L+Q6KGM"
    Exit = "6YCA5Ye6"
    NoDoneTasks = "5rKh5pyJ5bey5a6M5oiQ5Lu75Yqh"
    CreatedAt = "5Yib5bu65pe26Ze0"
    CompletedAt = "5a6M5oiQ5pe26Ze0"
    PomodoroCount = "55Wq6IyE5pWw"
    NoTaskSelected = "5pyq6YCJ5oup5Lu75Yqh"
    EnterTaskFirst = "6K+35YWI6L6T5YWl5Lu75Yqh5YaF5a6544CC"
    WorkMinutes = "5bel5L2c5YiG6ZKf"
    ShortBreakMinutes = "55+t5LyR5oGv5YiG6ZKf"
    Opacity = "5LiN6YCP5piO5bqm"
    TaskFontSize = "5Lu75Yqh5a2X5Y+3"
    TopMost = "572u6aG2"
    DataCheckDone = "5pWw5o2u5qOA5p+l5a6M5oiQ"
    TasksFileReadable = "5Lu75Yqh5paH5Lu25Y+v6K+75Y+W44CC"
    SettingsSaved = "6K6+572u5bey5L+d5a2Y"
    TaskAdded = "5Lu75Yqh5bey5re75Yqg"
    TaskCompleted = "5Lu75Yqh5bey5a6M5oiQ"
    TaskUncompleted = "5Lu75Yqh5bey5oGi5aSN"
    DailyArchiveTime = "5q+P5pel57uT566X5pe26Ze0"
    DailyArchivedTasks = "5bey6Ieq5Yqo5b2S5qGj5a6M5oiQ5Lu75Yqh"
    ScheduledToday = "5bey5a6J5o6S5Yiw5LuK5pel"
    Focusing = "5LiT5rOo5Lit"
    NoOpenTasks = "5pqC5peg5Lu75Yqh"
    NoTodayTasks = "5LuK5pel5pqC5peg5Lu75Yqh"
    ClickTaskHint = "5Y+z6ZSu5Lu75Yqh5pON5L2c77yM5ouW5Yqo5o6S5bqP"
    Language = "6K+t6KiA"
    Chinese = "5Lit5paH"
    English = "6Iux5paH"
    GeneralSettings = "6YCa55So6K6+572u"
    PomodoroSettings = "55Wq6IyE6ZKf6K6+572u"
    WorkMusic = "5LiT5rOo6Z+z5LmQ"
    BreakMusic = "5LyR5oGv6Z+z5LmQ"
    WorkMusicLoop = "5LiT5rOo5b6q546v"
    BreakMusicLoop = "5LyR5oGv5b6q546v"
    Select = "6YCJ5oup"
    Default = "6buY6K6k"
    DefaultSettings = "6buY6K6k6K6+572u"
    AudioSelected = "5bey6YCJ5oup6Z+z6aKR"
    AudioFile = "6Z+z6aKR5paH5Lu2"
    LoopIcon = "4oa7"
    LoopOnIcon = "4oa7"
    LoopOffIcon = "4oqY"
    BreakFocusing = "5LyR5oGv5Lit"
    BreakDone = "5LyR5oGv57uT5p2f"
    AppAlreadyRunning = "5p6B566A5qGM6Z2i55Wq6IyE5bey57uP5Zyo6L+Q6KGM44CC"
}

$script:TextEn = @{
    AppTitle = "Minimal Desktop Pomodoro"
    TaskList = "Tasks"
    TodayList = "Today"
    Pomodoro = "Timer"
    More = "More"
    Close = "×"
    Today = "Today"
    InputHint = "Type a task, then press Enter"
    Add = "Add"
    OpenTasks = "Open tasks"
    TodayTasks = "Today"
    Done = "Done"
    Settings = "Settings"
    DataCheck = "Data check"
    StartPomodoro = "Start timer"
    PomodoroMenu = "Timer"
    Complete = "Complete"
    CompleteTaskMenu = "Complete task"
    Cancel = "Cancel"
    ScheduleToday = "Schedule today"
    RemoveFromToday = "Remove from today"
    EndTask = "Archive task"
    PinToTop = "Pin to top"
    ReminderTime = "Reminder"
    DueDate = "Due date"
    EditTask = "Edit task"
    TaskDetails = "Task details"
    TaskTitle = "Task title"
    TaskNotes = "Task notes"
    TaskLinks = "Links / files"
    OpenTaskLink = "Open link / file"
    NoTaskLink = "No link or file to open"
    EstimatedPomodoros = "Estimated pomodoros"
    ActualPomodoros = "Actual pomodoros"
    UncompleteTaskMenu = "Mark not done"
    Help = "Help"
    HelpTitle = "UI help"
    HelpQuick = "Quick help"
    HelpDiagram = "Interface diagram"
    HelpRules = "Operation rules"
    HelpShortcuts = "Shortcuts"
    HelpUpdate = "Update / restart"
    RestartApp = "Restart current version"
    OpenAppFolder = "Open app folder"
    UpdateFromGit = "Update from Git and restart"
    DesktopShortcutMenu = "Add desktop shortcut"
    UpdateInfo = "Update info"
    HelpSponsor = "Support / sponsor"
    HelpAboutGovernance = "About / open-source governance"
    HelpText = "Tasks/Today: left click selects, double click runs the default action, right click opens actions, drag to reorder.`nWindow: drag from the top band of the first row, resize from edges, move near the bottom to show input and navigation.`nWatermark: click ~ for a translucent always-on-top reminder. In watermark mode, clicks pass through except over the triangle. Click the triangle to exit.`nShortcuts: Enter adds from the input box; F2 edits the selected title; Ctrl+double click opens links/files; Enter saves title edits and Esc cancels.`nHelp: left click ? for quick help; right click ? for diagram, rules, shortcuts, support, and governance.`nTimer: start from Today or Timer. Pause changes to Continue."
    HelpDiagramText = "Top right: ? help, ~ watermark, triangle exits watermark.`nFirst-row top band: drag the window.`nTask row: left click selects, double click runs the default action, right click opens actions, F2 edits the title, drag to reorder.`nBottom area: move near it to show input and navigation; - collapses to one row, square expands to ten rows, X closes."
    HelpRulesText = "Blank area: left click clears selection.`nTask input: type '2 task' to insert at position 2; no number appends to the end.`nTasks view: double click schedules to Today; click again after selecting or press F2 to edit the title.`nToday view: double click starts a timer; right click offers timer, complete, edit, and more.`nWatermark: only the triangle is interactive; other clicks pass through."
    HelpShortcutsText = "Input box: Enter adds the task.`nTask lists: F2 edits the selected task title; double click runs the default action; Ctrl+double click opens the link/file.`nTitle edit: Enter saves, Esc cancels."
    UpdateInfoText = "No Git remote is configured for this folder. After local edits, choose Restart current version. For distributed copies, download the latest version from the source or mirror and replace the program files; keep data and config to preserve personal data and settings."
    UpdateGitConfirm = "The app will close, run git pull --ff-only in the background, then restart. If it fails, open the app folder and check update.log."
    UpdatingAndRestarting = "Updating and restarting"
    DesktopShortcutPromptTitle = "Add desktop shortcut?"
    DesktopShortcutPromptBody = "Start from the desktop next time without opening the extracted folder."
    DesktopShortcutPromptHint = "Asked once; you can add it later from the Help menu."
    DesktopShortcutAdd = "Add"
    DesktopShortcutSkip = "Not now"
    DesktopShortcutInstalled = "Desktop shortcut added"
    DesktopShortcutInstallFailed = "Desktop shortcut failed"
    DesktopShortcutAlreadyExists = "Desktop shortcut already exists"
    HelpSponsorText = "Minimal Desktop Pomodoro is a free and open-source project. This version has no ads, no forced login, and no paywall for basic features.`nIf this tool helps you, you can support maintenance by reporting issues, improving docs, sharing usage feedback, or sponsoring.`nThe sponsor path stays low frequency: it only appears in the Help right-click menu, never in the main workflow, and never as a popup reminder."
    HelpAboutGovernanceText = "This tool prioritizes local data, light weight, and low interruption.`nOpen-source positioning: basic features stay free, governance stays transparent, and changes are evaluated before implementation.`nGovernance principles: user data stays local; features are restrained by default; new entry points are evaluated for frequency and distraction."
    Watermark = "Watermark"
    ExitWatermark = "Exit watermark"
    UnboundFocus = "Unbound focus"
    Start = "Start"
    Pause = "Pause"
    Continue = "Continue"
    Stop = "Stop"
    Reset = "Reset"
    CurrentTask = "Current task"
    SaveSettings = "Save"
    SoundReminder = "Sound"
    StartSoundReminder = "Start sound"
    EndSoundReminder = "End sound"
    ColorReminder = "Color cue"
    TaskbarReminder = "Taskbar flash"
    ToastReminder = "System notification"
    DataOk = "Data OK"
    NoTasksFile = "Task data file missing. It will be created."
    PomodoroDone = "Timer done"
    PomodoroLogged = "Timer logged."
    PomodoroInterrupted = "Timer interrupted"
    TimerAlreadyRunning = "Timer is already running."
    Exit = "Exit"
    NoDoneTasks = "No completed tasks"
    CreatedAt = "Created"
    CompletedAt = "Completed"
    PomodoroCount = "Pomodoros"
    NoTaskSelected = "No task selected"
    EnterTaskFirst = "Enter a task first."
    WorkMinutes = "Work min"
    ShortBreakMinutes = "Break min"
    Opacity = "Opacity"
    TaskFontSize = "Task font size"
    TopMost = "Topmost"
    DataCheckDone = "Data check done"
    TasksFileReadable = "Task file is readable."
    SettingsSaved = "Settings saved"
    TaskAdded = "Task added"
    TaskCompleted = "Task completed"
    TaskUncompleted = "Task restored"
    DailyArchiveTime = "Daily settlement"
    DailyArchivedTasks = "Completed tasks archived"
    ScheduledToday = "Scheduled today"
    Focusing = "Focusing"
    NoOpenTasks = "No tasks"
    NoTodayTasks = "No today tasks"
    ClickTaskHint = "Right-click tasks; drag to reorder"
    Language = "Language"
    Chinese = "Chinese"
    English = "English"
    GeneralSettings = "General"
    PomodoroSettings = "Pomodoro"
    WorkMusic = "Focus music"
    BreakMusic = "Break music"
    WorkMusicLoop = "Focus loop"
    BreakMusicLoop = "Break loop"
    Select = "Select"
    Default = "Default"
    DefaultSettings = "Defaults"
    AudioSelected = "Audio selected"
    AudioFile = "Audio file"
    LoopIcon = "4oa7"
    BreakFocusing = "On break"
    BreakDone = "Break done"
    AppAlreadyRunning = "Minimal Desktop Pomodoro is already running."
}

function T([string]$Key) {
    if ($Key -in @("LoopIcon", "LoopOnIcon", "LoopOffIcon")) {
        return [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($script:TextB64[$Key]))
    }
    $language = "zh-CN"
    if ($null -ne $script:Settings -and ($script:Settings.PSObject.Properties.Name -contains "Language")) {
        $language = [string]$script:Settings.Language
    }
    if ($language -eq "en-US" -and $script:TextEn.ContainsKey($Key)) {
        return $script:TextEn[$Key]
    }
    return [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($script:TextB64[$Key]))
}

